DROP TABLE IF EXISTS `#__j4s_properties`;
DROP TABLE IF EXISTS `#__j4s_prop_values`;
DROP TABLE IF EXISTS `#__j4s_types`;
DROP TABLE IF EXISTS `#__j4s_type_prop`;

CREATE TABLE IF NOT EXISTS `#__j4schema_properties` (
  `id_properties` varchar(255) NOT NULL,
  `pr_comment` text NOT NULL,
  `pr_comment_plain` text NOT NULL,
  `pr_ranges` varchar(255) NOT NULL,
  `pr_url` varchar(255) NOT NULL,
  PRIMARY KEY (`id_properties`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `#__j4schema_properties` (`id_properties`, `pr_comment`, `pr_comment_plain`, `pr_ranges`, `pr_url`) VALUES
('about', 'The subject matter of the content.', 'The subject matter of the content.', '', 'http://schema.org/about'),
('acceptsReservations', 'Either <code>Yes/No</code>, or a URL at which reservations can be made.', 'Either Yes/No, or a URL at which reservations can be made.', '', 'http://schema.org/acceptsReservations'),
('actors', 'A cast member of the movie, TV series, season, or episode, or video.', 'A cast member of the movie, TV series, season, or episode, or video.', '', 'http://schema.org/actors'),
('address', 'Physical address of the item.', 'Physical address of the item.', '', 'http://schema.org/address'),
('addressCountry', 'The country. For example, USA. You can also provide the two-letter <a href="http://en.wikipedia.org/wiki/ISO_3166-1" target="new">ISO 3166-1 alpha-2 country code</a>.', 'The country. For example, USA. You can also provide the two-letter ISO 3166-1 alpha-2 country code.', '', 'http://schema.org/addressCountry'),
('addressLocality', 'The locality. For example, Mountain View.', 'The locality. For example, Mountain View.', '', 'http://schema.org/addressLocality'),
('addressRegion', 'The region. For example, CA.', 'The region. For example, CA.', '', 'http://schema.org/addressRegion'),
('affiliation', 'An organization that this person is affiliated with. For example, a school/university, a club, or a team.', 'An organization that this person is affiliated with. For example, a school/university, a club, or a team.', '', 'http://schema.org/affiliation'),
('aggregateRating', 'The overall rating, based on a collection of reviews or ratings, of the item.', 'The overall rating, based on a collection of reviews or ratings, of the item.', '', 'http://schema.org/aggregateRating'),
('albums', '', '', '', 'http://schema.org/albums'),
('alumni', 'Alumni of educational organization.', 'Alumni of educational organization.', '', 'http://schema.org/alumni'),
('alumniOf', 'An educational organizations that the person is an alumni of.', 'An educational organizations that the person is an alumni of.', '', 'http://schema.org/alumniOf'),
('articleBody', 'The actual body of the article.', 'The actual body of the article.', '', 'http://schema.org/articleBody'),
('articleSection', 'Articles may belong to one or more ''sections'' in a magazine or newspaper, such as Sports, Lifestyle, etc.', 'Articles may belong to one or more ''sections'' in a magazine or newspaper, such as Sports, Lifestyle, etc.', '', 'http://schema.org/articleSection'),
('attendees', 'A person attending the event.', 'A person attending the event.', '', 'http://schema.org/attendees'),
('audio', 'An embeded audio object or URL associated with the content.', 'An embeded audio object or URL associated with the content.', '', 'http://schema.org/audio'),
('author', 'The author of this content. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangabely.', 'The author of this content. Please note that author is special in that HTML 5 provides a special mechanism for indicating authorship via the rel tag. That is equivalent to this and may be used interchangabely.', '', 'http://schema.org/author'),
('availability', 'The availability of this itemâ€”for example In stock, Out of stock, Pre-order, etc.', 'The availability of this itemâ€”for example In stock, Out of stock, Pre-order, etc.', '', 'http://schema.org/availability'),
('awards', 'Awards won by this person or for this creative work.', 'Awards won by this person or for this creative work.', '', 'http://schema.org/awards'),
('bestRating', 'The highest value allowed in this rating system. If bestRating is omitted, 5 is assumed.', 'The highest value allowed in this rating system. If bestRating is omitted, 5 is assumed.', '', 'http://schema.org/bestRating'),
('birthDate', 'Date of birth.', 'Date of birth.', '', 'http://schema.org/birthDate'),
('bitrate', 'The bitrate of the media object.', 'The bitrate of the media object.', '', 'http://schema.org/bitrate'),
('blogPosts', 'The postings that are part of this blog', 'The postings that are part of this blog', '', 'http://schema.org/blogPosts'),
('bookEdition', 'The edition of the book.', 'The edition of the book.', '', 'http://schema.org/bookEdition'),
('bookFormat', 'The format of the book.', 'The format of the book.', '', 'http://schema.org/bookFormat'),
('branchOf', 'The larger organization that this local business is a branch of, if any.', 'The larger organization that this local business is a branch of, if any.', '', 'http://schema.org/branchOf'),
('brand', 'The brand of the product.', 'The brand of the product.', '', 'http://schema.org/brand'),
('breadcrumb', 'A set of links that can help a user understand and navigate a website hierarchy.', 'A set of links that can help a user understand and navigate a website hierarchy.', '', 'http://schema.org/breadcrumb'),
('byArtist', 'The artist that performed this album or recording.', 'The artist that performed this album or recording.', '', 'http://schema.org/byArtist'),
('calories', 'The number of calories', 'The number of calories', '', 'http://schema.org/calories'),
('caption', 'The caption for this object.', 'The caption for this object.', '', 'http://schema.org/caption'),
('carbohydrateContent', 'The number of grams of carbohydrates.', 'The number of grams of carbohydrates.', '', 'http://schema.org/carbohydrateContent'),
('children', 'A child of the person.', 'A child of the person.', '', 'http://schema.org/children'),
('cholesterolContent', 'The number of milligrams of cholesterol.', 'The number of milligrams of cholesterol.', '', 'http://schema.org/cholesterolContent'),
('colleagues', 'A colleague of the person.', 'A colleague of the person.', '', 'http://schema.org/colleagues'),
('contactPoints', 'A contact point for a person or organization.', 'A contact point for a person or organization.', '', 'http://schema.org/contactPoints'),
('contactType', 'A person or organization can have different contact points, for different purposes. For example, a sales contact point, a PR contact point and so on. This property is used to specify the kind of contact point.', 'A person or organization can have different contact points, for different purposes. For example, a sales contact point, a PR contact point and so on. This property is used to specify the kind of contact point.', '', 'http://schema.org/contactType'),
('containedIn', 'The basic containment relation between places.', 'The basic containment relation between places.', '', 'http://schema.org/containedIn'),
('contentLocation', 'The location of the content.', 'The location of the content.', '', 'http://schema.org/contentLocation'),
('contentRating', 'Official rating of a piece of contentâ€”for example,''MPAA PG-13''.', 'Official rating of a piece of contentâ€”for example,''MPAA PG-13''.', '', 'http://schema.org/contentRating'),
('contentSize', 'File size in (mega/kilo) bytes.', 'File size in (mega/kilo) bytes.', '', 'http://schema.org/contentSize'),
('contentURL', 'Actual bytes of the media object, for example the image file or video file.', 'Actual bytes of the media object, for example the image file or video file.', '', 'http://schema.org/contentURL'),
('cookTime', 'The time it takes to actually cook the dish, in <a href="http://en.wikipedia.org/wiki/ISO_8601" target="new">ISO 8601 duration format</a>.', 'The time it takes to actually cook the dish, in ISO 8601 duration format.', '', 'http://schema.org/cookTime'),
('cookingMethod', 'The method of cooking, such as Frying, Steaming, ...', 'The method of cooking, such as Frying, Steaming, ...', '', 'http://schema.org/cookingMethod'),
('currenciesAccepted', 'The currency accepted (in <a href="http://en.wikipedia.org/wiki/ISO_4217" target="new">ISO 4217 currency format</a>).', 'The currency accepted (in ISO 4217 currency format).', '', 'http://schema.org/currenciesAccepted'),
('datePublished', 'Date of first broadcast/publication.', 'Date of first broadcast/publication.', '', 'http://schema.org/datePublished'),
('deathDate', 'Date of death.', 'Date of death.', '', 'http://schema.org/deathDate'),
('description', 'A short description of the item.', 'A short description of the item.', '', 'http://schema.org/description'),
('director', 'The director of the movie, TV episode, or series.', 'The director of the movie, TV episode, or series.', '', 'http://schema.org/director'),
('duration', 'The duration of the item (movie, audio recording, event, etc.) in <a href="http://en.wikipedia.org/wiki/ISO_8601" target="new">ISO 8601 date format</a>.', 'The duration of the item (movie, audio recording, event, etc.) in ISO 8601 date format.', '', 'http://schema.org/duration'),
('editor', 'Editor for this content.', 'Editor for this content.', '', 'http://schema.org/editor'),
('elevation', 'The elevation of a location.', 'The elevation of a location.', '', 'http://schema.org/elevation'),
('email', 'Email address.', 'Email address.', '', 'http://schema.org/email'),
('embedURL', 'A URL pointing to a player for a specific video. In general, this is the information in the <code>src</code> element of an <code>embed</code> tag and should not be the same as the content of the <code>loc</code> tag.', 'A URL pointing to a player for a specific video. In general, this is the information in the src element of an embed tag and should not be the same as the content of the loc tag.', '', 'http://schema.org/embedURL'),
('employees', 'People working for this organization.', 'People working for this organization.', '', 'http://schema.org/employees'),
('encodesCreativeWork', 'The creative work encoded by this media object', 'The creative work encoded by this media object', '', 'http://schema.org/encodesCreativeWork'),
('encodingFormat', 'mp3, mpeg4, etc.', 'mp3, mpeg4, etc.', '', 'http://schema.org/encodingFormat'),
('encodings', 'The media objects that encode this creative work', 'The media objects that encode this creative work', '', 'http://schema.org/encodings'),
('endDate', 'The end date and time of the event (in <a href="http://en.wikipedia.org/wiki/ISO_8601" target="new">ISO 8601 date format</a>).', 'The end date and time of the event (in ISO 8601 date format).', '', 'http://schema.org/endDate'),
('episodeNumber', 'The episode number.', 'The episode number.', '', 'http://schema.org/episodeNumber'),
('episodes', 'The episode of a TV series or season.', 'The episode of a TV series or season.', '', 'http://schema.org/episodes'),
('events', 'The events held at this place or organization.', 'The events held at this place or organization.', '', 'http://schema.org/events'),
('exifData', 'exif data for this object.', 'exif data for this object.', '', 'http://schema.org/exifData'),
('expires', 'Date the content expires and is no longer useful or available. Useful for videos.', 'Date the content expires and is no longer useful or available. Useful for videos.', '', 'http://schema.org/expires'),
('fatContent', 'The number of grams of fat.', 'The number of grams of fat.', '', 'http://schema.org/fatContent'),
('faxNumber', 'The fax number.', 'The fax number.', '', 'http://schema.org/faxNumber'),
('fiberContent', 'The number of grams of fiber.', 'The number of grams of fiber.', '', 'http://schema.org/fiberContent'),
('follows', 'The most generic uni-directional social relation.', 'The most generic uni-directional social relation.', '', 'http://schema.org/follows'),
('founders', 'A person who founded this organization.', 'A person who founded this organization.', '', 'http://schema.org/founders'),
('foundingDate', 'The date that this organization was founded.', 'The date that this organization was founded.', '', 'http://schema.org/foundingDate'),
('gender', 'Gender of the person.', 'Gender of the person.', '', 'http://schema.org/gender'),
('genre', 'Genre of the creative work', 'Genre of the creative work', '', 'http://schema.org/genre'),
('geo', 'The geo coordinates of the place.', 'The geo coordinates of the place.', '', 'http://schema.org/geo'),
('headline', 'Headline of the article', 'Headline of the article', '', 'http://schema.org/headline'),
('height', 'The height of the media object.', 'The height of the media object.', '', 'http://schema.org/height'),
('highPrice', 'The highest price of all offers available.', 'The highest price of all offers available.', '', 'http://schema.org/highPrice'),
('homeLocation', 'A contact location for a person''s residence.', 'A contact location for a person''s residence.', '', 'http://schema.org/homeLocation'),
('illustrator', 'The illustrator of the book.', 'The illustrator of the book.', '', 'http://schema.org/illustrator'),
('image', 'URL of an image of the item.', 'URL of an image of the item.', '', 'http://schema.org/image'),
('inAlbum', 'The album to which this recording belongs.', 'The album to which this recording belongs.', '', 'http://schema.org/inAlbum'),
('inLanguage', 'The language of the content. please use one of the language codes from the <a href="http://tools.ietf.org/html/bcp47">IETF BCP 47 standard.</a>', 'The language of the content. please use one of the language codes from the IETF BCP 47 standard.', '', 'http://schema.org/inLanguage'),
('inPlaylist', 'The playlist to which this recording belongs.', 'The playlist to which this recording belongs.', '', 'http://schema.org/inPlaylist'),
('ingredients', 'An ingredient used in the recipe.', 'An ingredient used in the recipe.', '', 'http://schema.org/ingredients'),
('interactionCount', 'A count of a specific user interactions with this itemâ€”for example, <code>20 UserLikes</code>, <code>5 UserComments</code>, or <code>300 UserDownloads</code>. The user interaction type should be one of the sub types of <a href="http://schema.org/UserInteraction">UserInteraction</a>.', 'A count of a specific user interactions with this itemâ€”for example, 20 UserLikes, 5 UserComments, or 300 UserDownloads. The user interaction type should be one of the sub types of UserInteraction.', '', 'http://schema.org/interactionCount'),
('isFamilyFriendly', 'Indicates whether this content is family friendly.', 'Indicates whether this content is family friendly.', '', 'http://schema.org/isFamilyFriendly'),
('isPartOf', 'Indicates the collection or gallery to which the item belongs.', 'Indicates the collection or gallery to which the item belongs.', '', 'http://schema.org/isPartOf'),
('isbn', 'The ISBN of the book.', 'The ISBN of the book.', '', 'http://schema.org/isbn'),
('itemCondition', 'The condition of the item for saleâ€”for example New, Refurbished, Used, etc.', 'The condition of the item for saleâ€”for example New, Refurbished, Used, etc.', '', 'http://schema.org/itemCondition'),
('itemListElement', 'A single list item.', 'A single list item.', '', 'http://schema.org/itemListElement'),
('itemOffered', 'The item being sold.', 'The item being sold.', '', 'http://schema.org/itemOffered'),
('itemReviewed', 'The item that is being reviewed/rated.', 'The item that is being reviewed/rated.', '', 'http://schema.org/itemReviewed'),
('jobTitle', 'The job title of the person (for example, Financial Manager).', 'The job title of the person (for example, Financial Manager).', '', 'http://schema.org/jobTitle'),
('keywords', 'The keywords/tags used to describe this content.', 'The keywords/tags used to describe this content.', '', 'http://schema.org/keywords'),
('knows', 'The most generic bi-directional social/work relation.', 'The most generic bi-directional social/work relation.', '', 'http://schema.org/knows'),
('latitude', 'The latitude of a location. For example <code>37.42242</code>.', 'The latitude of a location. For example 37.42242.', '', 'http://schema.org/latitude'),
('location', 'The location of the event or organization.', 'The location of the event or organization.', '', 'http://schema.org/location'),
('longitude', 'The longitude of a location. For example <code>-122.08585</code>.', 'The longitude of a location. For example -122.08585.', '', 'http://schema.org/longitude'),
('lowPrice', 'The lowest price of all offers available.', 'The lowest price of all offers available.', '', 'http://schema.org/lowPrice'),
('mainContentOfPage', 'Indicates if this web page element is the main subject of the page.', 'Indicates if this web page element is the main subject of the page.', '', 'http://schema.org/mainContentOfPage'),
('manufacturer', 'The manufacturer of the product.', 'The manufacturer of the product.', '', 'http://schema.org/manufacturer'),
('maps', 'A URL to a map of the place.', 'A URL to a map of the place.', '', 'http://schema.org/maps'),
('memberOf', 'An organization to which the person belongs.', 'An organization to which the person belongs.', '', 'http://schema.org/memberOf'),
('members', 'A member of this organization.', 'A member of this organization.', '', 'http://schema.org/members'),
('menu', 'Either the actual menu or a URL of the menu.', 'Either the actual menu or a URL of the menu.', '', 'http://schema.org/menu'),
('model', 'The model of the product.', 'The model of the product.', '', 'http://schema.org/model'),
('musicBy', 'The composer of the movie or TV soundtrack.', 'The composer of the movie or TV soundtrack.', '', 'http://schema.org/musicBy'),
('musicGroupMember', 'A member of the music groupâ€”for example, John, Paul, George, or Ringo.', 'A member of the music groupâ€”for example, John, Paul, George, or Ringo.', '', 'http://schema.org/musicGroupMember'),
('name', 'The name of the item.', 'The name of the item.', '', 'http://schema.org/name'),
('nationality', 'Nationality of the person.', 'Nationality of the person.', '', 'http://schema.org/nationality'),
('numTracks', 'The number of tracks in this album or playlist.', 'The number of tracks in this album or playlist.', '', 'http://schema.org/numTracks'),
('numberOfEpisodes', 'The number of episodes in this season or series.', 'The number of episodes in this season or series.', '', 'http://schema.org/numberOfEpisodes'),
('numberOfPages', 'The number of pages in the book.', 'The number of pages in the book.', '', 'http://schema.org/numberOfPages'),
('nutrition', 'Nutrition information about the recipe.', 'Nutrition information about the recipe.', '', 'http://schema.org/nutrition'),
('offerCount', 'The number of offers for the product.', 'The number of offers for the product.', '', 'http://schema.org/offerCount'),
('offers', 'An offer to sell this itemâ€”for example, an offer to sell a product, the DVD of a movie, or tickets to an event.', 'An offer to sell this itemâ€”for example, an offer to sell a product, the DVD of a movie, or tickets to an event.', '', 'http://schema.org/offers'),
('openingHours', 'The opening hours for a business. Opening hours can be specified as a weekly time range, starting with days, then times per day. Multiple days can be listed with commas '','' separating each day. Day or time ranges are specified using a hyphen ''-''.<br />- Days are specified using the following two-letter combinations: <code>Mo</code>, <code>Tu</code>, <code>We</code>, <code>Th</code>, <code>Fr</code>, <code>Sa</code>, <code>Su</code>.<br />- Times are specified using 24:00 time. For example, 3pm is specified as <code>15:00</code>.<br />Here is an example: <code>&lt;time itemprop="openingHours" datetime="Tu,Th 16:00-20:00"&gt;Tuesdays and Thursdays 4-8pm&lt;/time&gt;</code>', 'The opening hours for a business. Opening hours can be specified as a weekly time range, starting with days, then times per day. Multiple days can be listed with commas '','' separating each day. Day or time ranges are specified using a hyphen ''-''.- Days are specified using the following two-letter combinations: Mo, Tu, We, Th, Fr, Sa, Su.- Times are specified using 24:00 time. For example, 3pm is specified as 15:00.Here is an example: <time itemprop="openingHours" datetime="Tu,Th 16:00-20:00">Tuesdays and Thursdays 4-8pm</time>', '', 'http://schema.org/openingHours'),
('parents', 'A parents of the person.', 'A parents of the person.', '', 'http://schema.org/parents'),
('partOfSeason', 'The season to which this episode belongs.', 'The season to which this episode belongs.', '', 'http://schema.org/partOfSeason'),
('partOfTVSeries', 'The TV series to which this episode or season belongs.', 'The TV series to which this episode or season belongs.', '', 'http://schema.org/partOfTVSeries'),
('paymentAccepted', 'Cash, credit card, etc.', 'Cash, credit card, etc.', '', 'http://schema.org/paymentAccepted'),
('performerIn', 'Event that this person is a performer or participant in.', 'Event that this person is a performer or participant in.', '', 'http://schema.org/performerIn'),
('performers', 'The main performer or performers of the eventâ€”for example, a presenter, musician, or actor.', 'The main performer or performers of the eventâ€”for example, a presenter, musician, or actor.', '', 'http://schema.org/performers'),
('photos', 'Photographs of this place.', 'Photographs of this place.', '', 'http://schema.org/photos'),
('playerType', 'Player type requiredâ€”for example, Flash or Silverlight.', 'Player type requiredâ€”for example, Flash or Silverlight.', '', 'http://schema.org/playerType'),
('postOfficeBoxNumber', 'The post offce box number for PO box addresses.', 'The post offce box number for PO box addresses.', '', 'http://schema.org/postOfficeBoxNumber'),
('postalCode', 'The postal code. For example, 94043.', 'The postal code. For example, 94043.', '', 'http://schema.org/postalCode'),
('prepTime', 'The length of time it takes to prepare the recipe, in <a href="http://en.wikipedia.org/wiki/ISO_8601" target="new">ISO 8601 duration format</a>.', 'The length of time it takes to prepare the recipe, in ISO 8601 duration format.', '', 'http://schema.org/prepTime'),
('price', 'The offer price of the product.', 'The offer price of the product.', '', 'http://schema.org/price'),
('priceCurrency', 'The currency (in 3-letter <a href="http://en.wikipedia.org/wiki/ISO_4217">ISO 4217 format</a>) of the offer price.', 'The currency (in 3-letter ISO 4217 format) of the offer price.', '', 'http://schema.org/priceCurrency'),
('priceRange', 'The price range of the business, for example <code>$$$</code>.', 'The price range of the business, for example $$$.', '', 'http://schema.org/priceRange'),
('priceValidUntil', 'The date after which the price is no longer available.', 'The date after which the price is no longer available.', '', 'http://schema.org/priceValidUntil'),
('primaryImageOfPage', 'Indicates the main image on the page', 'Indicates the main image on the page', '', 'http://schema.org/primaryImageOfPage'),
('producer', 'The producer of the movie, TV series, season, or episode, or video.', 'The producer of the movie, TV series, season, or episode, or video.', '', 'http://schema.org/producer'),
('productID', 'The product identifier, such as ISBN. For example: <code>&lt;meta itemprop=''productID'' content=''isbn:123-456-789''/&gt;</code>.', 'The product identifier, such as ISBN. For example: <meta itemprop=''productID'' content=''isbn:123-456-789''/>.', '', 'http://schema.org/productID'),
('productionCompany', 'The production company or studio that made the movie, TV series, season, or episode, or video.', 'The production company or studio that made the movie, TV series, season, or episode, or video.', '', 'http://schema.org/productionCompany'),
('proteinContent', 'The number of grams of protein.', 'The number of grams of protein.', '', 'http://schema.org/proteinContent'),
('publisher', 'The publisher of the creative work.', 'The publisher of the creative work.', '', 'http://schema.org/publisher'),
('ratingCount', 'The count of total number of ratings.', 'The count of total number of ratings.', '', 'http://schema.org/ratingCount'),
('ratingValue', 'The rating for the content.', 'The rating for the content.', '', 'http://schema.org/ratingValue'),
('recipeCategory', 'The category of the recipeâ€”for example, appetizer, entree, etc.', 'The category of the recipeâ€”for example, appetizer, entree, etc.', '', 'http://schema.org/recipeCategory'),
('recipeCuisine', 'The cuisine of the recipe (for example, French or Ethopian).', 'The cuisine of the recipe (for example, French or Ethopian).', '', 'http://schema.org/recipeCuisine'),
('recipeInstructions', 'The steps to make the dish.', 'The steps to make the dish.', '', 'http://schema.org/recipeInstructions'),
('recipeYield', 'The quantity produced by the recipe (for example, number of people served, number of servings, etc).', 'The quantity produced by the recipe (for example, number of people served, number of servings, etc).', '', 'http://schema.org/recipeYield'),
('regionsAllowed', 'The regions where the media is allowed. If not specified, then it''s assumed to be allowed everywhere. Specify the countries in <a href="http://en.wikipedia.org/wiki/ISO_3166" target="new">ISO 3166 format</a>.', 'The regions where the media is allowed. If not specified, then it''s assumed to be allowed everywhere. Specify the countries in ISO 3166 format.', '', 'http://schema.org/regionsAllowed'),
('relatedTo', 'The most generic familial relation.', 'The most generic familial relation.', '', 'http://schema.org/relatedTo'),
('representativeOfPage', 'Indicates whether this image is representative of the content of the page.', 'Indicates whether this image is representative of the content of the page.', '', 'http://schema.org/representativeOfPage'),
('requiresSubscription', 'Indicates if use of the media require a subscription  (either paid or free). Allowed values are <code>yes</code> or <code>no</code>.', 'Indicates if use of the media require a subscription  (either paid or free). Allowed values are yes or no.', '', 'http://schema.org/requiresSubscription'),
('reviewBody', 'The actual body of the review', 'The actual body of the review', '', 'http://schema.org/reviewBody'),
('reviewCount', 'The count of total number of reviews.', 'The count of total number of reviews.', '', 'http://schema.org/reviewCount'),
('reviewRating', 'The rating given in this review. Note that reviews can themselves be rated. The <code>reviewRating</code> applies to rating given by the review. The <code>rating</code> property applies to the review itself, as a creative work.', 'The rating given in this review. Note that reviews can themselves be rated. The reviewRating applies to rating given by the review. The rating property applies to the review itself, as a creative work.', '', 'http://schema.org/reviewRating'),
('reviews', 'Review of the item.', 'Review of the item.', '', 'http://schema.org/reviews'),
('saturatedFatContent', 'The number of grams of saturated fat.', 'The number of grams of saturated fat.', '', 'http://schema.org/saturatedFatContent'),
('seasonNumber', 'The season number.', 'The season number.', '', 'http://schema.org/seasonNumber'),
('seasons', 'The seasons of the TV series.', 'The seasons of the TV series.', '', 'http://schema.org/seasons'),
('seller', 'The seller of the product.', 'The seller of the product.', '', 'http://schema.org/seller'),
('servesCuisine', 'The cuisine of the restaurant.', 'The cuisine of the restaurant.', '', 'http://schema.org/servesCuisine'),
('servingSize', 'The serving size, in terms of the number of volume or mass', 'The serving size, in terms of the number of volume or mass', '', 'http://schema.org/servingSize'),
('siblings', 'A sibling of the person.', 'A sibling of the person.', '', 'http://schema.org/siblings'),
('significantLinks', 'The most significant URLs on the page. Typically, these are the non-navigation links that are clicked on the most', 'The most significant URLs on the page. Typically, these are the non-navigation links that are clicked on the most', '', 'http://schema.org/significantLinks'),
('sodiumContent', 'The number of milligrams of sodium.', 'The number of milligrams of sodium.', '', 'http://schema.org/sodiumContent'),
('spouse', 'The person''s spouse.', 'The person''s spouse.', '', 'http://schema.org/spouse'),
('startDate', 'The start date and time of the event (in <a href="http://en.wikipedia.org/wiki/ISO_8601" target="new">ISO 8601 date format</a>).', 'The start date and time of the event (in ISO 8601 date format).', '', 'http://schema.org/startDate'),
('streetAddress', 'The street address. For example, 1600 Amphitheatre Pkwy.', 'The street address. For example, 1600 Amphitheatre Pkwy.', '', 'http://schema.org/streetAddress'),
('subEvents', 'Events that are a part of this event. For example, a conference event includes many presentations, each are subEvents of the conference.', 'Events that are a part of this event. For example, a conference event includes many presentations, each are subEvents of the conference.', '', 'http://schema.org/subEvents'),
('sugarContent', 'The number of grams of sugar.', 'The number of grams of sugar.', '', 'http://schema.org/sugarContent'),
('superEvent', 'An event that this event is a part of. For example, a collection of individual music performances might each have a music festival as their superEvent.', 'An event that this event is a part of. For example, a collection of individual music performances might each have a music festival as their superEvent.', '', 'http://schema.org/superEvent'),
('telephone', 'The telephone number.', 'The telephone number.', '', 'http://schema.org/telephone'),
('thumbnail', 'Thumbnail image for an image or video.', 'Thumbnail image for an image or video.', '', 'http://schema.org/thumbnail'),
('totalTime', 'The total time it takes to prepare and cook the recipe, in <a href="http://en.wikipedia.org/wiki/ISO_8601" target="new">ISO 8601 duration format</a>.', 'The total time it takes to prepare and cook the recipe, in ISO 8601 duration format.', '', 'http://schema.org/totalTime'),
('tracks', 'A music recording (track)â€”usually a single song.', 'A music recording (track)â€”usually a single song.', '', 'http://schema.org/tracks'),
('trailer', 'The trailer of the movie or TV series, season, or episode.', 'The trailer of the movie or TV series, season, or episode.', '', 'http://schema.org/trailer'),
('transFatContent', 'The number of grams of trans fat.', 'The number of grams of trans fat.', '', 'http://schema.org/transFatContent'),
('unsaturatedFatContent', 'The number of grams of unsaturated fat.', 'The number of grams of unsaturated fat.', '', 'http://schema.org/unsaturatedFatContent'),
('uploadDate', 'Date when this media object was uploaded to this site.', 'Date when this media object was uploaded to this site.', '', 'http://schema.org/uploadDate'),
('url', 'URL of the item.', 'URL of the item.', '', 'http://schema.org/url'),
('video', 'An embeded video object or URL associated with the content.', 'An embeded video object or URL associated with the content.', '', 'http://schema.org/video'),
('width', 'The width of the media object.', 'The width of the media object.', '', 'http://schema.org/width'),
('workLocation', 'A contact location for a person''s place of work.', 'A contact location for a person''s place of work.', '', 'http://schema.org/workLocation'),
('worksFor', 'Organizations that the person works for.', 'Organizations that the person works for.', '', 'http://schema.org/worksFor'),
('worstRating', 'The lowest value allowed in this rating system. If worstRating is omitted, 1 is assumed.', 'The lowest value allowed in this rating system. If worstRating is omitted, 1 is assumed.', '', 'http://schema.org/worstRating'),
('EBook', '', '', '', 'http://schema.org/EBook'),
('Hardcover', '', '', '', 'http://schema.org/Hardcover'),
('Paperback', '', '', '', 'http://schema.org/Paperback'),
('False', '', '', '', 'http://schema.org/False'),
('True', '', '', '', 'http://schema.org/True'),
('Discontinued', '', '', '', 'http://schema.org/Discontinued'),
('InStock', '', '', '', 'http://schema.org/InStock'),
('InStoreOnly', '', '', '', 'http://schema.org/InStoreOnly'),
('OnlineOnly', '', '', '', 'http://schema.org/OnlineOnly'),
('OutOfStock', '', '', '', 'http://schema.org/OutOfStock'),
('PreOrder', '', '', '', 'http://schema.org/PreOrder'),
('DamagedCondition', '', '', '', 'http://schema.org/DamagedCondition'),
('NewCondition', '', '', '', 'http://schema.org/NewCondition'),
('RefurbishedCondition', '', '', '', 'http://schema.org/RefurbishedCondition'),
('UsedCondition', '', '', '', 'http://schema.org/UsedCondition');

CREATE TABLE IF NOT EXISTS `#__j4schema_prop_values` (
  `pv_id_properties` varchar(50) NOT NULL,
  `pv_value` varchar(50) NOT NULL,
  `pv_enum` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`pv_id_properties`,`pv_value`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `#__j4schema_prop_values` (`pv_id_properties`, `pv_value`, `pv_enum`) VALUES
('about', 'Thing', 0),
('acceptsReservations', 'Text', 0),
('actors', 'Person', 0),
('address', 'PostalAddress', 0),
('addressCountry', 'Country', 0),
('addressLocality', 'Text', 0),
('addressRegion', 'Text', 0),
('affiliation', 'Organization', 0),
('aggregateRating', 'AggregateRating', 0),
('albums', 'MusicAlbum', 0),
('alumni', 'Person', 0),
('alumniOf', 'EducationalOrganization', 0),
('articleBody', 'Text', 0),
('articleSection', 'Text', 0),
('attendees', 'Person', 0),
('attendees', 'Organization', 0),
('audio', 'AudioObject', 0),
('author', 'Person', 0),
('author', 'Organization', 0),
('availability', 'ItemAvailability', 0),
('awards', 'Text', 0),
('bestRating', 'Number', 0),
('bestRating', 'Text', 0),
('birthDate', 'Date', 0),
('bitrate', 'Text', 0),
('blogPosts', 'BlogPosting', 0),
('bookEdition', 'Text', 0),
('bookFormat', 'BookFormatType', 0),
('branchOf', 'Organization', 0),
('brand', 'Organization', 0),
('breadcrumb', 'Text', 0),
('byArtist', 'MusicGroup', 0),
('caption', 'Text', 0),
('carbohydrateContent', 'Mass', 0),
('children', 'Person', 0),
('cholesterolContent', 'Mass', 0),
('colleagues', 'Person', 0),
('contactPoints', 'ContactPoint', 0),
('contactType', 'Text', 0),
('containedIn', 'Place', 0),
('contentLocation', 'Place', 0),
('contentRating', 'Text', 0),
('contentSize', 'Text', 0),
('contentURL', 'Text', 0),
('cookTime', 'Duration', 0),
('cookingMethod', 'Text', 0),
('currenciesAccepted', 'Text', 0),
('datePublished', 'Date', 0),
('deathDate', 'Date', 0),
('description', 'Text', 0),
('director', 'Person', 0),
('duration', 'Duration', 0),
('editor', 'Person', 0),
('elevation', 'Number', 0),
('elevation', 'Text', 0),
('email', 'Text', 0),
('embedURL', 'Text', 0),
('employees', 'Person', 0),
('encodesCreativeWork', 'CreativeWork', 0),
('encodingFormat', 'Text', 0),
('encodings', 'MediaObject', 0),
('endDate', 'Date', 0),
('episodeNumber', 'Number', 0),
('episodes', 'TVEpisode', 0),
('events', 'Event', 0),
('exifData', 'Text', 0),
('expires', 'Date', 0),
('fatContent', 'Mass', 0),
('faxNumber', 'Text', 0),
('fiberContent', 'Mass', 0),
('follows', 'Person', 0),
('founders', 'Person', 0),
('foundingDate', 'Date', 0),
('gender', 'Text', 0),
('genre', 'Text', 0),
('geo', 'GeoCoordinates', 0),
('headline', 'Text', 0),
('height', 'Distance', 0),
('highPrice', 'Number', 0),
('highPrice', 'Text', 0),
('homeLocation', 'Place', 0),
('homeLocation', 'ContactPoint', 0),
('illustrator', 'Person', 0),
('image', 'URL', 0),
('inAlbum', 'MusicAlbum', 0),
('inLanguage', 'Text', 0),
('inPlaylist', 'MusicPlaylist', 0),
('ingredients', 'Text', 0),
('interactionCount', 'Text', 0),
('isFamilyFriendly', 'Boolean', 0),
('isPartOf', 'CollectionPage', 0),
('isbn', 'Text', 0),
('itemCondition', 'OfferItemCondition', 0),
('itemListElement', 'Text', 0),
('itemOffered', 'Product', 0),
('itemReviewed', 'Thing', 0),
('jobTitle', 'Text', 0),
('keywords', 'Text', 0),
('knows', 'Person', 0),
('latitude', 'Number', 0),
('latitude', 'Text', 0),
('location', 'PostalAddress', 0),
('location', 'Place', 0),
('longitude', 'Number', 0),
('longitude', 'Text', 0),
('lowPrice', 'Number', 0),
('lowPrice', 'Text', 0),
('mainContentOfPage', 'WebPageElement', 0),
('manufacturer', 'Organization', 0),
('maps', 'Map', 0),
('memberOf', 'Organization', 0),
('members', 'Person', 0),
('members', 'Organization', 0),
('menu', 'Text', 0),
('model', 'Text', 0),
('musicBy', 'MusicGroup', 0),
('musicBy', 'Person', 0),
('musicGroupMember', 'Person', 0),
('name', 'Text', 0),
('nationality', 'Country', 0),
('numTracks', 'Integer', 0),
('numberOfEpisodes', 'Number', 0),
('numberOfPages', 'Integer', 0),
('nutrition', 'NutritionInformation', 0),
('offerCount', 'Integer', 0),
('offers', 'Offer', 0),
('openingHours', 'Duration', 0),
('parents', 'Person', 0),
('partOfSeason', 'TVSeason', 0),
('partOfTVSeries', 'TVSeries', 0),
('paymentAccepted', 'Text', 0),
('performerIn', 'Event', 0),
('performers', 'Person', 0),
('performers', 'Organization', 0),
('photos', 'Photograph', 0),
('photos', 'ImageObject', 0),
('playerType', 'Text', 0),
('postOfficeBoxNumber', 'Text', 0),
('postalCode', 'Text', 0),
('prepTime', 'Duration', 0),
('price', 'Number', 0),
('price', 'Text', 0),
('priceCurrency', 'Text', 0),
('priceRange', 'Text', 0),
('priceValidUntil', 'Date', 0),
('primaryImageOfPage', 'ImageObject', 0),
('producer', 'Person', 0),
('productID', 'Text', 0),
('productionCompany', 'Organization', 0),
('proteinContent', 'Mass', 0),
('publisher', 'Organization', 0),
('ratingCount', 'Number', 0),
('ratingValue', 'Text', 0),
('recipeCategory', 'Text', 0),
('recipeCuisine', 'Text', 0),
('recipeInstructions', 'Text', 0),
('recipeYield', 'Text', 0),
('regionsAllowed', 'Place', 0),
('relatedTo', 'Person', 0),
('representativeOfPage', 'Boolean', 0),
('requiresSubscription', 'Boolean', 0),
('reviewBody', 'Text', 0),
('reviewCount', 'Number', 0),
('reviewRating', 'Rating', 0),
('reviews', 'Review', 0),
('saturatedFatContent', 'Mass', 0),
('seasonNumber', 'Integer', 0),
('seasons', 'TVSeason', 0),
('seller', 'Organization', 0),
('servesCuisine', 'Text', 0),
('servingSize', 'Text', 0),
('siblings', 'Person', 0),
('significantLinks', 'URL', 0),
('sodiumContent', 'Mass', 0),
('spouse', 'Person', 0),
('startDate', 'Date', 0),
('streetAddress', 'Text', 0),
('subEvents', 'Event', 0),
('sugarContent', 'Mass', 0),
('superEvent', 'Event', 0),
('telephone', 'Text', 0),
('thumbnail', 'ImageObject', 0),
('totalTime', 'Duration', 0),
('tracks', 'MusicRecording', 0),
('trailer', 'VideoObject', 0),
('transFatContent', 'Mass', 0),
('unsaturatedFatContent', 'Mass', 0),
('uploadDate', 'Date', 0),
('url', 'Text', 0),
('video', 'VideoObject', 0),
('width', 'Distance', 0),
('workLocation', 'Place', 0),
('workLocation', 'ContactPoint', 0),
('worksFor', 'Organization', 0),
('worstRating', 'Number', 0),
('worstRating', 'Text', 0),
('EBook', 'Enum', 1),
('Hardcover', 'Enum', 1),
('Paperback', 'Enum', 1),
('False', 'Enum', 1),
('True', 'Enum', 1),
('Discontinued', 'Enum', 1),
('InStock', 'Enum', 1),
('InStoreOnly', 'Enum', 1),
('OnlineOnly', 'Enum', 1),
('OutOfStock', 'Enum', 1),
('PreOrder', 'Enum', 1),
('DamagedCondition', 'Enum', 1),
('NewCondition', 'Enum', 1),
('RefurbishedCondition', 'Enum', 1),
('UsedCondition', 'Enum', 1);

CREATE TABLE IF NOT EXISTS `#__j4schema_types` (
  `id_types` varchar(50) NOT NULL,
  `ty_parent` varchar(50) NOT NULL,
  `ty_comment` text NOT NULL,
  `ty_comment_plain` text NOT NULL,
  `ty_label` varchar(50) NOT NULL,
  `ty_url` varchar(100) NOT NULL,
  `ty_children` tinyint(4) NOT NULL,
  PRIMARY KEY (`id_types`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `#__j4schema_types` (`id_types`, `ty_parent`, `ty_comment`, `ty_comment_plain`, `ty_label`, `ty_url`, `ty_children`) VALUES
('AboutPage', 'WebPage', 'Web page type: About page.', 'Web page type: About page.', 'About Page', 'http://schema.org/AboutPage', 0),
('AccountingService', 'FinancialService', 'Accountancy business.', 'Accountancy business.', 'Accounting Service', 'http://schema.org/AccountingService', 0),
('AdministrativeArea', 'Place', 'A geographical region under the jurisdiction of a particular government.', 'A geographical region under the jurisdiction of a particular government.', 'Administrative Area', 'http://schema.org/AdministrativeArea', 3),
('AdultEntertainment', 'EntertainmentBusiness', 'An adult entertainment establishment.', 'An adult entertainment establishment.', 'Adult Entertainment', 'http://schema.org/AdultEntertainment', 0),
('AggregateOffer', 'Offer', 'When a single product that has different offers (for example, the same pair of shoes is offered by different merchants), then AggregateOffer can be used.', 'When a single product that has different offers (for example, the same pair of shoes is offered by different merchants), then AggregateOffer can be used.', 'Aggregate Offer', 'http://schema.org/AggregateOffer', 0),
('AggregateRating', 'Rating', 'The average rating based on multiple ratings or reviews.', 'The average rating based on multiple ratings or reviews.', 'Aggregate Rating', 'http://schema.org/AggregateRating', 0),
('Airport', 'CivicStructure', 'An airport.', 'An airport.', 'Airport', 'http://schema.org/Airport', 0),
('AmusementPark', 'EntertainmentBusiness', 'An amusement park.', 'An amusement park.', 'Amusement Park', 'http://schema.org/AmusementPark', 0),
('AnimalShelter', 'LocalBusiness', 'Animal shelter.', 'Animal shelter.', 'Animal Shelter', 'http://schema.org/AnimalShelter', 0),
('ApartmentComplex', 'Residence', 'Residence type: Apartment complex.', 'Residence type: Apartment complex.', 'Apartment Complex', 'http://schema.org/ApartmentComplex', 0),
('Aquarium', 'CivicStructure', 'Aquarium.', 'Aquarium.', 'Aquarium', 'http://schema.org/Aquarium', 0),
('ArtGallery', 'EntertainmentBusiness', 'An art gallery.', 'An art gallery.', 'Art Gallery', 'http://schema.org/ArtGallery', 0),
('Article', 'CreativeWork', 'An article, such as a news article or piece of investigative report. Newspapers and magazines have articles of many different types and this is intended to cover them all.', 'An article, such as a news article or piece of investigative report. Newspapers and magazines have articles of many different types and this is intended to cover them all.', 'Article', 'http://schema.org/Article', 3),
('Attorney', 'ProfessionalService', 'Professional service: Attorney.', 'Professional service: Attorney.', 'Attorney', 'http://schema.org/Attorney', 0),
('AudioObject', 'MediaObject', 'An audio file.', 'An audio file.', 'Audio Object', 'http://schema.org/AudioObject', 0),
('AutoBodyShop', 'AutomotiveBusiness', 'Auto body shop.', 'Auto body shop.', 'Auto Body Shop', 'http://schema.org/AutoBodyShop', 0),
('AutoDealer', 'AutomotiveBusiness', 'An car dealership.', 'An car dealership.', 'Auto Dealer', 'http://schema.org/AutoDealer', 0),
('AutomatedTeller', 'FinancialService', 'ATM/cash machine.', 'ATM/cash machine.', 'Automated Teller', 'http://schema.org/AutomatedTeller', 0),
('AutomotiveBusiness', 'LocalBusiness', 'Car repair, sales, or parts.', 'Car repair, sales, or parts.', 'Automotive Business', 'http://schema.org/AutomotiveBusiness', 9),
('AutoPartsStore', 'Store', 'An auto parts store.', 'An auto parts store.', 'Auto Parts Store', 'http://schema.org/AutoPartsStore', 0),
('AutoRental', 'AutomotiveBusiness', 'A car rental business.', 'A car rental business.', 'Auto Rental', 'http://schema.org/AutoRental', 0),
('AutoRepair', 'AutomotiveBusiness', 'Car repair business.', 'Car repair business.', 'Auto Repair', 'http://schema.org/AutoRepair', 0),
('AutoWash', 'AutomotiveBusiness', 'A car wash business.', 'A car wash business.', 'Auto Wash', 'http://schema.org/AutoWash', 0),
('Bakery', 'FoodEstablishment', 'A bakery.', 'A bakery.', 'Bakery', 'http://schema.org/Bakery', 0),
('BankOrCreditUnion', 'FinancialService', 'Bank or credit union.', 'Bank or credit union.', 'Bank Or Credit Union', 'http://schema.org/BankOrCreditUnion', 0),
('BarOrPub', 'FoodEstablishment', 'A bar or pub.', 'A bar or pub.', 'Bar Or Pub', 'http://schema.org/BarOrPub', 0),
('Beach', 'CivicStructure', 'Beach.', 'Beach.', 'Beach', 'http://schema.org/Beach', 0),
('BeautySalon', 'HealthAndBeautyBusiness', 'Beauty salon.', 'Beauty salon.', 'Beauty Salon', 'http://schema.org/BeautySalon', 0),
('BedAndBreakfast', 'LodgingBusiness', 'Bed and breakfast.', 'Bed and breakfast.', 'Bed And Breakfast', 'http://schema.org/BedAndBreakfast', 0),
('BikeStore', 'Store', 'A bike store.', 'A bike store.', 'Bike Store', 'http://schema.org/BikeStore', 0),
('Blog', 'CreativeWork', 'A blog', 'A blog', 'Blog', 'http://schema.org/Blog', 0),
('BlogPosting', 'Article', 'A blog post.', 'A blog post.', 'Blog Posting', 'http://schema.org/BlogPosting', 0),
('BodyOfWater', 'Landform', 'A body of water, such as a sea, ocean, or lake.', 'A body of water, such as a sea, ocean, or lake.', 'Body Of Water', 'http://schema.org/BodyOfWater', 8),
('Book', 'CreativeWork', 'A book.', 'A book.', 'Book', 'http://schema.org/Book', 0),
('BookFormatType', 'Enumeration', 'The publication format of the book.', 'The publication format of the book.', 'Book Format Type', 'http://schema.org/BookFormatType', 0),
('BookStore', 'Store', 'A bookstore.', 'A bookstore.', 'Book Store', 'http://schema.org/BookStore', 0),
('Boolean', 'DataType', 'Boolean: True or False.', 'Boolean: True or False.', 'Boolean', 'http://schema.org/Boolean', 0),
('BowlingAlley', 'SportsActivityLocation', 'A bowling alley.', 'A bowling alley.', 'Bowling Alley', 'http://schema.org/BowlingAlley', 0),
('Brewery', 'FoodEstablishment', 'Brewery.', 'Brewery.', 'Brewery', 'http://schema.org/Brewery', 0),
('BuddhistTemple', 'PlaceOfWorship', 'A Buddhist temple.', 'A Buddhist temple.', 'Buddhist Temple', 'http://schema.org/BuddhistTemple', 0),
('BusinessEvent', 'Event', 'Event type: Business event.', 'Event type: Business event.', 'Business Event', 'http://schema.org/BusinessEvent', 0),
('BusStation', 'CivicStructure', 'A bus station.', 'A bus station.', 'Bus Station', 'http://schema.org/BusStation', 0),
('BusStop', 'CivicStructure', 'A bus stop.', 'A bus stop.', 'Bus Stop', 'http://schema.org/BusStop', 0),
('CafeOrCoffeeShop', 'FoodEstablishment', 'A cafe or coffee shop.', 'A cafe or coffee shop.', 'Cafe Or Coffee Shop', 'http://schema.org/CafeOrCoffeeShop', 0),
('Campground', 'CivicStructure', 'A campground.', 'A campground.', 'Campground', 'http://schema.org/Campground', 0),
('Canal', 'BodyOfWater', '', '', 'Canal', 'http://schema.org/Canal', 0),
('Casino', 'EntertainmentBusiness', 'A casino.', 'A casino.', 'Casino', 'http://schema.org/Casino', 0),
('CatholicChurch', 'PlaceOfWorship', 'A Catholic church.', 'A Catholic church.', 'Catholic Church', 'http://schema.org/CatholicChurch', 0),
('Cemetery', 'CivicStructure', 'A graveyard.', 'A graveyard.', 'Cemetery', 'http://schema.org/Cemetery', 0),
('CheckoutPage', 'WebPage', 'Web page type: Checkout page.', 'Web page type: Checkout page.', 'Checkout Page', 'http://schema.org/CheckoutPage', 0),
('ChildCare', 'LocalBusiness', 'A Childcare center.', 'A Childcare center.', 'Child Care', 'http://schema.org/ChildCare', 0),
('ChildrensEvent', 'Event', 'Event type: Children''s event.', 'Event type: Children''s event.', 'Childrens Event', 'http://schema.org/ChildrensEvent', 0),
('Church', 'PlaceOfWorship', 'A church.', 'A church.', 'Church', 'http://schema.org/Church', 0),
('City', 'AdministrativeArea', 'A city or town.', 'A city or town.', 'City', 'http://schema.org/City', 0),
('CityHall', 'GovernmentBuilding', 'A city hall.', 'A city hall.', 'City Hall', 'http://schema.org/CityHall', 0),
('CivicStructure', 'Place', 'A public structure, such as a town hall or concert hall.', 'A public structure, such as a town hall or concert hall.', 'Civic Structure', 'http://schema.org/CivicStructure', 27),
('ClothingStore', 'Store', 'A clothing store.', 'A clothing store.', 'Clothing Store', 'http://schema.org/ClothingStore', 0),
('CollectionPage', 'WebPage', 'Web page type: Collection page.', 'Web page type: Collection page.', 'Collection Page', 'http://schema.org/CollectionPage', 2),
('CollegeOrUniversity', 'EducationalOrganization', 'A college, university, or other third-level educational institution.', 'A college, university, or other third-level educational institution.', 'College Or University', 'http://schema.org/CollegeOrUniversity', 0),
('ComedyClub', 'EntertainmentBusiness', 'A comedy club.', 'A comedy club.', 'Comedy Club', 'http://schema.org/ComedyClub', 0),
('ComedyEvent', 'Event', 'Event type: Comedy event.', 'Event type: Comedy event.', 'Comedy Event', 'http://schema.org/ComedyEvent', 0),
('ComputerStore', 'Store', 'A computer store.', 'A computer store.', 'Computer Store', 'http://schema.org/ComputerStore', 0),
('ContactPage', 'WebPage', 'Web page type: Contact page.', 'Web page type: Contact page.', 'Contact Page', 'http://schema.org/ContactPage', 0),
('ContactPoint', 'StructuredValue', 'A contact pointâ€”for example, a Customer Complaints department.', 'A contact pointâ€”for example, a Customer Complaints department.', 'Contact Point', 'http://schema.org/ContactPoint', 1),
('Continent', 'Landform', 'One of the continents (for example, Europe or Africa).', 'One of the continents (for example, Europe or Africa).', 'Continent', 'http://schema.org/Continent', 0),
('ConvenienceStore', 'Store', 'A convenience store.', 'A convenience store.', 'Convenience Store', 'http://schema.org/ConvenienceStore', 0),
('Corporation', 'Organization', 'Organization: A business corporation.', 'Organization: A business corporation.', 'Corporation', 'http://schema.org/Corporation', 0),
('Country', 'AdministrativeArea', 'A country.', 'A country.', 'Country', 'http://schema.org/Country', 0),
('Courthouse', 'GovernmentBuilding', 'A courthouse.', 'A courthouse.', 'Courthouse', 'http://schema.org/Courthouse', 0),
('CreativeWork', 'Thing', 'The most generic kind of creative work, including books, movies, photographs, software programs, etc.', 'The most generic kind of creative work, including books, movies, photographs, software programs, etc.', 'Creative Work', 'http://schema.org/CreativeWork', 19),
('Crematorium', 'CivicStructure', 'A crematorium.', 'A crematorium.', 'Crematorium', 'http://schema.org/Crematorium', 0),
('DanceEvent', 'Event', 'Event type: A social dance.', 'Event type: A social dance.', 'Dance Event', 'http://schema.org/DanceEvent', 0),
('DanceGroup', 'PerformingGroup', 'A dance groupâ€”for example, the Alvin Ailey Dance Theater or Riverdance.', 'A dance groupâ€”for example, the Alvin Ailey Dance Theater or Riverdance.', 'Dance Group', 'http://schema.org/DanceGroup', 0),
('DataType', '', 'The basic data types such as Integers, Strings, etc.', 'The basic data types such as Integers, Strings, etc.', 'Data Type', 'http://schema.org/DataType', 4),
('Date', 'DataType', 'A date value in <a href="http://en.wikipedia.org/wiki/ISO_8601" target="new">ISO 8601 date format</a>.', 'A date value in ISO 8601 date format.', 'Date', 'http://schema.org/Date', 0),
('DaySpa', 'HealthAndBeautyBusiness', 'A day spa.', 'A day spa.', 'Day Spa', 'http://schema.org/DaySpa', 0),
('DefenceEstablishment', 'GovernmentBuilding', 'A defence establishment, such as an army or navy base.', 'A defence establishment, such as an army or navy base.', 'Defence Establishment', 'http://schema.org/DefenceEstablishment', 0),
('Dentist', 'MedicalOrganization', 'A dentist.', 'A dentist.', 'Dentist', 'http://schema.org/Dentist', 0),
('DepartmentStore', 'Store', 'A department store.', 'A department store.', 'Department Store', 'http://schema.org/DepartmentStore', 0),
('Distance', 'Quantity', 'Properties that take Distances as values are of the form ''<Number> <Length unit of measure>''. E.g., ''7 ft''', 'Properties that take Distances as values are of the form ''<Number> <Length unit of measure>''. E.g., ''7 ft''', 'Distance', 'http://schema.org/Distance', 0),
('DryCleaningOrLaundry', 'LocalBusiness', 'A dry-cleaning business.', 'A dry-cleaning business.', 'Dry Cleaning Or Laundry', 'http://schema.org/DryCleaningOrLaundry', 0),
('Duration', 'Quantity', 'Quantity: Duration (use  <a href="http://en.wikipedia.org/wiki/ISO_8601" target="new">ISO 8601 duration format</a>).', 'Quantity: Duration (use  ISO 8601 duration format).', 'Duration', 'http://schema.org/Duration', 0),
('EducationalOrganization', 'Organization', 'An educational organization.', 'An educational organization.', 'Educational Organization', 'http://schema.org/EducationalOrganization', 6),
('EducationEvent', 'Event', 'Event type: Education event.', 'Event type: Education event.', 'Education Event', 'http://schema.org/EducationEvent', 0),
('Electrician', 'HomeAndConstructionBusiness', 'An electrician.', 'An electrician.', 'Electrician', 'http://schema.org/Electrician', 0),
('ElectronicsStore', 'Store', 'An electronics store.', 'An electronics store.', 'Electronics Store', 'http://schema.org/ElectronicsStore', 0),
('ElementarySchool', 'EducationalOrganization', 'An elementary school.', 'An elementary school.', 'Elementary School', 'http://schema.org/ElementarySchool', 0),
('Embassy', 'GovernmentBuilding', 'An embassy.', 'An embassy.', 'Embassy', 'http://schema.org/Embassy', 0),
('EmergencyService', 'LocalBusiness', 'An emergency service, such as a fire station or ER.', 'An emergency service, such as a fire station or ER.', 'Emergency Service', 'http://schema.org/EmergencyService', 3),
('EmploymentAgency', 'LocalBusiness', 'An employment agency.', 'An employment agency.', 'Employment Agency', 'http://schema.org/EmploymentAgency', 0),
('EntertainmentBusiness', 'LocalBusiness', 'A business providing entertainment.', 'A business providing entertainment.', 'Entertainment Business', 'http://schema.org/EntertainmentBusiness', 7),
('Enumeration', 'Intangible', 'Lists or enumerationsâ€”for example, a list of cuisines or music genres, etc.', 'Lists or enumerationsâ€”for example, a list of cuisines or music genres, etc.', 'Enumeration', 'http://schema.org/Enumeration', 3),
('Event', 'Thing', 'An event happening at a certain time at a certain location.', 'An event happening at a certain time at a certain location.', 'Event', 'http://schema.org/Event', 15),
('EventVenue', 'CivicStructure', 'An event venue.', 'An event venue.', 'Event Venue', 'http://schema.org/EventVenue', 0),
('ExerciseGym', 'SportsActivityLocation', 'A gym.', 'A gym.', 'Exercise Gym', 'http://schema.org/ExerciseGym', 0),
('FastFoodRestaurant', 'FoodEstablishment', 'A fast-food restaurant.', 'A fast-food restaurant.', 'Fast Food Restaurant', 'http://schema.org/FastFoodRestaurant', 0),
('Festival', 'Event', 'Event type: Festival.', 'Event type: Festival.', 'Festival', 'http://schema.org/Festival', 0),
('FinancialService', 'LocalBusiness', 'Financial services business.', 'Financial services business.', 'Financial Service', 'http://schema.org/FinancialService', 4),
('FireStation', 'CivicStructure', 'A fire station. With firemen.', 'A fire station. With firemen.', 'Fire Station', 'http://schema.org/FireStation', 0),
('Float', 'Number', 'Data type: Floating number.', 'Data type: Floating number.', 'Float', 'http://schema.org/Float', 0),
('Florist', 'Store', 'A florist.', 'A florist.', 'Florist', 'http://schema.org/Florist', 0),
('FoodEstablishment', 'LocalBusiness', 'A food-related business.', 'A food-related business.', 'Food Establishment', 'http://schema.org/FoodEstablishment', 8),
('FoodEvent', 'Event', 'Event type: Food event.', 'Event type: Food event.', 'Food Event', 'http://schema.org/FoodEvent', 0),
('FurnitureStore', 'Store', 'A furniture store.', 'A furniture store.', 'Furniture Store', 'http://schema.org/FurnitureStore', 0),
('GardenStore', 'Store', 'A garden store.', 'A garden store.', 'Garden Store', 'http://schema.org/GardenStore', 0),
('GasStation', 'AutomotiveBusiness', 'A gas station.', 'A gas station.', 'Gas Station', 'http://schema.org/GasStation', 0),
('GatedResidenceCommunity', 'Residence', 'Residence type: Gated community.', 'Residence type: Gated community.', 'Gated Residence Community', 'http://schema.org/GatedResidenceCommunity', 0),
('GeneralContractor', 'HomeAndConstructionBusiness', 'A general contractor.', 'A general contractor.', 'General Contractor', 'http://schema.org/GeneralContractor', 0),
('GeoCoordinates', 'StructuredValue', 'The geographic coordinates of a place or event.', 'The geographic coordinates of a place or event.', 'Geo Coordinates', 'http://schema.org/GeoCoordinates', 0),
('GolfCourse', 'SportsActivityLocation', 'A golf course.', 'A golf course.', 'Golf Course', 'http://schema.org/GolfCourse', 0),
('GovernmentBuilding', 'CivicStructure', 'A government building.', 'A government building.', 'Government Building', 'http://schema.org/GovernmentBuilding', 5),
('GovernmentOffice', 'LocalBusiness', 'A government officeâ€”for example, an IRS or DMV office.', 'A government officeâ€”for example, an IRS or DMV office.', 'Government Office', 'http://schema.org/GovernmentOffice', 1),
('GovernmentOrganization', 'Organization', 'A governmental organization or agency.', 'A governmental organization or agency.', 'Government Organization', 'http://schema.org/GovernmentOrganization', 0),
('GroceryStore', 'Store', 'A grocery store.', 'A grocery store.', 'Grocery Store', 'http://schema.org/GroceryStore', 0),
('HairSalon', 'HealthAndBeautyBusiness', 'A hair salon.', 'A hair salon.', 'Hair Salon', 'http://schema.org/HairSalon', 0),
('HardwareStore', 'Store', 'A hardware store.', 'A hardware store.', 'Hardware Store', 'http://schema.org/HardwareStore', 0),
('HealthAndBeautyBusiness', 'LocalBusiness', 'Health and beauty.', 'Health and beauty.', 'Health And Beauty Business', 'http://schema.org/HealthAndBeautyBusiness', 6),
('HealthClub', 'HealthAndBeautyBusiness', 'A health club.', 'A health club.', 'Health Club', 'http://schema.org/HealthClub', 0),
('HighSchool', 'EducationalOrganization', 'A high school.', 'A high school.', 'High School', 'http://schema.org/HighSchool', 0),
('HinduTemple', 'PlaceOfWorship', 'A Hindu temple.', 'A Hindu temple.', 'Hindu Temple', 'http://schema.org/HinduTemple', 0),
('HobbyShop', 'Store', 'A hobby store.', 'A hobby store.', 'Hobby Shop', 'http://schema.org/HobbyShop', 0),
('HomeAndConstructionBusiness', 'LocalBusiness', 'A construction business.', 'A construction business.', 'Home And Construction Business', 'http://schema.org/HomeAndConstructionBusiness', 8),
('HomeGoodsStore', 'Store', 'A home goods store.', 'A home goods store.', 'Home Goods Store', 'http://schema.org/HomeGoodsStore', 0),
('Hospital', 'MedicalOrganization', 'A hospital.', 'A hospital.', 'Hospital', 'http://schema.org/Hospital', 0),
('Hostel', 'LodgingBusiness', 'A hostel.', 'A hostel.', 'Hostel', 'http://schema.org/Hostel', 0),
('Hotel', 'LodgingBusiness', 'A hotel.', 'A hotel.', 'Hotel', 'http://schema.org/Hotel', 0),
('HousePainter', 'HomeAndConstructionBusiness', 'A house painting service.', 'A house painting service.', 'House Painter', 'http://schema.org/HousePainter', 0),
('HVACBusiness', 'HomeAndConstructionBusiness', 'An HVAC service.', 'An HVAC service.', 'HVAC Business', 'http://schema.org/HVACBusiness', 0),
('IceCreamShop', 'FoodEstablishment', 'An ice cream shop', 'An ice cream shop', 'Ice Cream Shop', 'http://schema.org/IceCreamShop', 0),
('ImageGallery', 'CollectionPage', 'Web page type: Image gallery page.', 'Web page type: Image gallery page.', 'Image Gallery', 'http://schema.org/ImageGallery', 0),
('ImageObject', 'MediaObject', 'An image file.', 'An image file.', 'Image Object', 'http://schema.org/ImageObject', 0),
('InsuranceAgency', 'FinancialService', 'Insurance agency.', 'Insurance agency.', 'Insurance Agency', 'http://schema.org/InsuranceAgency', 0),
('Intangible', 'Thing', 'A utility class that serves as the umbrella for a number of ''intangible'' things such as quantities, structured values, etc.', 'A utility class that serves as the umbrella for a number of ''intangible'' things such as quantities, structured values, etc.', 'Intangible', 'http://schema.org/Intangible', 6),
('Integer', 'Number', 'Data type: Integer.', 'Data type: Integer.', 'Integer', 'http://schema.org/Integer', 0),
('InternetCafe', 'LocalBusiness', 'An internet cafe.', 'An internet cafe.', 'Internet Cafe', 'http://schema.org/InternetCafe', 0),
('ItemAvailability', 'Enumeration', 'A list of possible product availablity options.', 'A list of possible product availablity options.', 'Item Availability', 'http://schema.org/ItemAvailability', 0),
('ItemList', 'CreativeWork', 'A list of items of any sortâ€”for example, Top 10 Movies About Weathermen, or Top 100 Party Songs. Not to be confused with HTML lists, which are often used only for formatting.', 'A list of items of any sortâ€”for example, Top 10 Movies About Weathermen, or Top 100 Party Songs. Not to be confused with HTML lists, which are often used only for formatting.', 'Item List', 'http://schema.org/ItemList', 0),
('ItemPage', 'WebPage', 'A page devoted to a single item, such as a particular product or hotel.', 'A page devoted to a single item, such as a particular product or hotel.', 'Item Page', 'http://schema.org/ItemPage', 0),
('JewelryStore', 'Store', 'A jewelry store.', 'A jewelry store.', 'Jewelry Store', 'http://schema.org/JewelryStore', 0),
('LakeBodyOfWater', 'BodyOfWater', 'A lake (for example, Lake Pontrachain).', 'A lake (for example, Lake Pontrachain).', 'Lake Body Of Water', 'http://schema.org/LakeBodyOfWater', 0),
('Landform', 'Place', 'A landform or physical feature.  Landform elements include mountains, plains, lakes, rivers, seascape and oceanic waterbody interface features such as bays, peninsulas, seas and so forth, including sub-aqueous terrain features such as submersed mountain ranges, volcanoes, and the great ocean basins.', 'A landform or physical feature.  Landform elements include mountains, plains, lakes, rivers, seascape and oceanic waterbody interface features such as bays, peninsulas, seas and so forth, including sub-aqueous terrain features such as submersed mountain ranges, volcanoes, and the great ocean basins.', 'Landform', 'http://schema.org/Landform', 4),
('LandmarksOrHistoricalBuildings', 'Place', 'An historical landmark or building.', 'An historical landmark or building.', 'Landmarks Or Historical Buildings', 'http://schema.org/LandmarksOrHistoricalBuildings', 0),
('Language', 'Intangible', 'Natural languages such as Spanish, Tamil, Hindi, English, etc. and programming languages such as Scheme and Lisp.', 'Natural languages such as Spanish, Tamil, Hindi, English, etc. and programming languages such as Scheme and Lisp.', 'Language', 'http://schema.org/Language', 0),
('LegislativeBuilding', 'GovernmentBuilding', 'A legislative buildingâ€”for example, the state capitol.', 'A legislative buildingâ€”for example, the state capitol.', 'Legislative Building', 'http://schema.org/LegislativeBuilding', 0),
('Library', 'LocalBusiness', 'A library.', 'A library.', 'Library', 'http://schema.org/Library', 0),
('LiquorStore', 'Store', 'A liquor store.', 'A liquor store.', 'Liquor Store', 'http://schema.org/LiquorStore', 0),
('LiteraryEvent', 'Event', 'Event type: Literary event.', 'Event type: Literary event.', 'Literary Event', 'http://schema.org/LiteraryEvent', 0),
('LocalBusiness', 'Organization', 'A particular physical business or branch of an organization. Examples of LocalBusiness include a restaurant, a particular branch of a restaurant chain, a branch of a bank, a medical practice, a club, a bowling alley, etc.', 'A particular physical business or branch of an organization. Examples of LocalBusiness include a restaurant, a particular branch of a restaurant chain, a branch of a bank, a medical practice, a club, a bowling alley, etc.', 'Local Business', 'http://schema.org/LocalBusiness', 27),
('Locksmith', 'HomeAndConstructionBusiness', 'A locksmith.', 'A locksmith.', 'Locksmith', 'http://schema.org/Locksmith', 0),
('LodgingBusiness', 'LocalBusiness', 'A lodging business, such as a motel, hotel, or inn.', 'A lodging business, such as a motel, hotel, or inn.', 'Lodging Business', 'http://schema.org/LodgingBusiness', 4),
('Map', 'CreativeWork', 'A map.', 'A map.', 'Map', 'http://schema.org/Map', 0),
('Mass', 'Quantity', 'Properties that take Mass as values are of the form ''<Number> <Mass unit of measure>''. E.g., ''7 kg''', 'Properties that take Mass as values are of the form ''<Number> <Mass unit of measure>''. E.g., ''7 kg''', 'Mass', 'http://schema.org/Mass', 0),
('MediaObject', 'CreativeWork', 'An image, video, or audio object embedded in a web page. Note that a creative work may have many media objects associated with it on the same web page. For example, a page about a single song (MusicRecording) may have a music video (VideoObject), and a high and low bandwidth audio stream (2 AudioObject''s).', 'An image, video, or audio object embedded in a web page. Note that a creative work may have many media objects associated with it on the same web page. For example, a page about a single song (MusicRecording) may have a music video (VideoObject), and a high and low bandwidth audio stream (2 AudioObject''s).', 'Media Object', 'http://schema.org/MediaObject', 4),
('MedicalClinic', 'MedicalOrganization', 'A medical clinic.', 'A medical clinic.', 'Medical Clinic', 'http://schema.org/MedicalClinic', 0),
('MedicalOrganization', 'LocalBusiness', 'A medical organization, such as a doctor''s office or clinic.', 'A medical organization, such as a doctor''s office or clinic.', 'Medical Organization', 'http://schema.org/MedicalOrganization', 7),
('MensClothingStore', 'Store', 'A men''s clothing store.', 'A men''s clothing store.', 'Mens Clothing Store', 'http://schema.org/MensClothingStore', 0),
('MiddleSchool', 'EducationalOrganization', 'A middle school.', 'A middle school.', 'Middle School', 'http://schema.org/MiddleSchool', 0),
('MobilePhoneStore', 'Store', 'A mobile-phone store.', 'A mobile-phone store.', 'Mobile Phone Store', 'http://schema.org/MobilePhoneStore', 0),
('Mosque', 'PlaceOfWorship', 'A mosque.', 'A mosque.', 'Mosque', 'http://schema.org/Mosque', 0),
('Motel', 'LodgingBusiness', 'A motel.', 'A motel.', 'Motel', 'http://schema.org/Motel', 0),
('MotorcycleDealer', 'AutomotiveBusiness', 'A motorcycle dealer.', 'A motorcycle dealer.', 'Motorcycle Dealer', 'http://schema.org/MotorcycleDealer', 0),
('MotorcycleRepair', 'AutomotiveBusiness', 'A motorcycle repair shop.', 'A motorcycle repair shop.', 'Motorcycle Repair', 'http://schema.org/MotorcycleRepair', 0),
('Mountain', 'Landform', 'A mountain, like Mount Whitney or Mount Everest', 'A mountain, like Mount Whitney or Mount Everest', 'Mountain', 'http://schema.org/Mountain', 0),
('Movie', 'CreativeWork', '', '', 'Movie', 'http://schema.org/Movie', 0),
('MovieRentalStore', 'Store', 'A movie rental store.', 'A movie rental store.', 'Movie Rental Store', 'http://schema.org/MovieRentalStore', 0),
('MovieTheater', 'EntertainmentBusiness', 'A movie theater.', 'A movie theater.', 'Movie Theater', 'http://schema.org/MovieTheater', 0),
('MovingCompany', 'HomeAndConstructionBusiness', 'A moving company.', 'A moving company.', 'Moving Company', 'http://schema.org/MovingCompany', 0),
('Museum', 'CivicStructure', 'A museum.', 'A museum.', 'Museum', 'http://schema.org/Museum', 0),
('MusicAlbum', 'MusicPlaylist', 'A collection of music tracks.', 'A collection of music tracks.', 'Music Album', 'http://schema.org/MusicAlbum', 0),
('MusicEvent', 'Event', 'Event type: Music event.', 'Event type: Music event.', 'Music Event', 'http://schema.org/MusicEvent', 0),
('MusicGroup', 'PerformingGroup', 'A musical group, such as a band, an orchestra, or a choir. Can also be a solo musician.', 'A musical group, such as a band, an orchestra, or a choir. Can also be a solo musician.', 'Music Group', 'http://schema.org/MusicGroup', 0),
('MusicPlaylist', 'CreativeWork', 'A collection of music tracks in playlist form.', 'A collection of music tracks in playlist form.', 'Music Playlist', 'http://schema.org/MusicPlaylist', 1),
('MusicRecording', 'CreativeWork', '', '', 'Music Recording', 'http://schema.org/MusicRecording', 0),
('MusicStore', 'Store', 'A music store.', 'A music store.', 'Music Store', 'http://schema.org/MusicStore', 0),
('MusicVenue', 'CivicStructure', 'A music venue.', 'A music venue.', 'Music Venue', 'http://schema.org/MusicVenue', 0),
('MusicVideoObject', 'MediaObject', 'A music video file.', 'A music video file.', 'Music Video Object', 'http://schema.org/MusicVideoObject', 0),
('NailSalon', 'HealthAndBeautyBusiness', 'A nail salon.', 'A nail salon.', 'Nail Salon', 'http://schema.org/NailSalon', 0),
('NewsArticle', 'Article', 'A news article', 'A news article', 'News Article', 'http://schema.org/NewsArticle', 0),
('NGO', 'Organization', 'Organization: Non-governmental Organization.', 'Organization: Non-governmental Organization.', 'NGO', 'http://schema.org/NGO', 0),
('NightClub', 'EntertainmentBusiness', 'A nightclub or discotheque.', 'A nightclub or discotheque.', 'Night Club', 'http://schema.org/NightClub', 0),
('Notary', 'ProfessionalService', 'A notary.', 'A notary.', 'Notary', 'http://schema.org/Notary', 0),
('Number', 'DataType', 'Data type: Number.', 'Data type: Number.', 'Number', 'http://schema.org/Number', 2),
('NutritionInformation', 'StructuredValue', 'Nutritional information about the recipe.', 'Nutritional information about the recipe.', 'Nutrition Information', 'http://schema.org/NutritionInformation', 0),
('OceanBodyOfWater', 'BodyOfWater', 'An ocean (for example, the Pacific).', 'An ocean (for example, the Pacific).', 'Ocean Body Of Water', 'http://schema.org/OceanBodyOfWater', 0),
('Offer', 'Intangible', 'An offer to sell an itemâ€”for example, an offer to sell a product, the DVD of a movie, or tickets to an event.', 'An offer to sell an itemâ€”for example, an offer to sell a product, the DVD of a movie, or tickets to an event.', 'Offer', 'http://schema.org/Offer', 1),
('OfferItemCondition', 'Enumeration', 'A list of possible conditions for the item for sale.', 'A list of possible conditions for the item for sale.', 'Offer Item Condition', 'http://schema.org/OfferItemCondition', 0),
('OfficeEquipmentStore', 'Store', 'An office equipment store.', 'An office equipment store.', 'Office Equipment Store', 'http://schema.org/OfficeEquipmentStore', 0),
('Optician', 'MedicalOrganization', 'An optician''s store.', 'An optician''s store.', 'Optician', 'http://schema.org/Optician', 0),
('Organization', 'Thing', 'An organization such as a school, NGO, corporation, club, etc.', 'An organization such as a school, NGO, corporation, club, etc.', 'Organization', 'http://schema.org/Organization', 7),
('OutletStore', 'Store', 'An outlet store.', 'An outlet store.', 'Outlet Store', 'http://schema.org/OutletStore', 0),
('Painting', 'CreativeWork', 'A painting.', 'A painting.', 'Painting', 'http://schema.org/Painting', 0),
('Park', 'CivicStructure', 'A park.', 'A park.', 'Park', 'http://schema.org/Park', 0),
('ParkingFacility', 'CivicStructure', 'A parking lot or other parking facility.', 'A parking lot or other parking facility.', 'Parking Facility', 'http://schema.org/ParkingFacility', 0),
('PawnShop', 'Store', 'A pawnstore.', 'A pawnstore.', 'Pawn Shop', 'http://schema.org/PawnShop', 0),
('PerformingArtsTheater', 'CivicStructure', 'A theatre or other performing art center.', 'A theatre or other performing art center.', 'Performing Arts Theater', 'http://schema.org/PerformingArtsTheater', 0),
('PerformingGroup', 'Organization', 'A performance group, such as a band, an orchestra, or a circus.', 'A performance group, such as a band, an orchestra, or a circus.', 'Performing Group', 'http://schema.org/PerformingGroup', 3),
('Person', 'Thing', 'A person (alive, dead, undead, or fictional).', 'A person (alive, dead, undead, or fictional).', 'Person', 'http://schema.org/Person', 0),
('PetStore', 'Store', 'A pet store.', 'A pet store.', 'Pet Store', 'http://schema.org/PetStore', 0),
('Pharmacy', 'MedicalOrganization', 'A pharmacy or drugstore.', 'A pharmacy or drugstore.', 'Pharmacy', 'http://schema.org/Pharmacy', 0),
('Photograph', 'CreativeWork', 'A photograph.', 'A photograph.', 'Photograph', 'http://schema.org/Photograph', 0),
('Physician', 'MedicalOrganization', 'A doctor''s office.', 'A doctor''s office.', 'Physician', 'http://schema.org/Physician', 0),
('Place', 'Thing', 'Entities that have a somewhat fixed, physical extension.', 'Entities that have a somewhat fixed, physical extension.', 'Place', 'http://schema.org/Place', 7),
('PlaceOfWorship', 'CivicStructure', 'Place of worship, such as a church, synagogue, or mosque.', 'Place of worship, such as a church, synagogue, or mosque.', 'Place Of Worship', 'http://schema.org/PlaceOfWorship', 6),
('Playground', 'CivicStructure', 'A playground.', 'A playground.', 'Playground', 'http://schema.org/Playground', 0),
('Plumber', 'HomeAndConstructionBusiness', 'A plumbing service.', 'A plumbing service.', 'Plumber', 'http://schema.org/Plumber', 0),
('PoliceStation', 'CivicStructure', 'A police station.', 'A police station.', 'Police Station', 'http://schema.org/PoliceStation', 0),
('Pond', 'BodyOfWater', '', '', 'Pond', 'http://schema.org/Pond', 0),
('PostalAddress', 'ContactPoint', 'The mailing address.', 'The mailing address.', 'Postal Address', 'http://schema.org/PostalAddress', 0),
('PostOffice', 'GovernmentOffice', 'A post office.', 'A post office.', 'Post Office', 'http://schema.org/PostOffice', 0),
('Preschool', 'EducationalOrganization', 'A preschool.', 'A preschool.', 'Preschool', 'http://schema.org/Preschool', 0),
('Product', 'Thing', 'A product is anything that is made available for saleâ€”for example, a pair of shoes, a concert ticket, or a car.', 'A product is anything that is made available for saleâ€”for example, a pair of shoes, a concert ticket, or a car.', 'Product', 'http://schema.org/Product', 0),
('ProfessionalService', 'LocalBusiness', 'Provider of professional services.', 'Provider of professional services.', 'Professional Service', 'http://schema.org/ProfessionalService', 10),
('ProfilePage', 'WebPage', 'Web page type: Profile page.', 'Web page type: Profile page.', 'Profile Page', 'http://schema.org/ProfilePage', 0),
('PublicSwimmingPool', 'SportsActivityLocation', 'A public swimming pool.', 'A public swimming pool.', 'Public Swimming Pool', 'http://schema.org/PublicSwimmingPool', 0),
('Quantity', 'Intangible', 'Quantities such as distance, time, mass, weight, etc. Particular instances of say Mass are entities like ''3 Kg'' or ''4 milligrams''.', 'Quantities such as distance, time, mass, weight, etc. Particular instances of say Mass are entities like ''3 Kg'' or ''4 milligrams''.', 'Quantity', 'http://schema.org/Quantity', 3),
('RadioStation', 'LocalBusiness', 'A radio station.', 'A radio station.', 'Radio Station', 'http://schema.org/RadioStation', 0),
('Rating', 'Intangible', 'The rating of the video.', 'The rating of the video.', 'Rating', 'http://schema.org/Rating', 1),
('RealEstateAgent', 'LocalBusiness', 'A real-estate agent.', 'A real-estate agent.', 'Real Estate Agent', 'http://schema.org/RealEstateAgent', 0),
('Recipe', 'CreativeWork', 'A recipe.', 'A recipe.', 'Recipe', 'http://schema.org/Recipe', 0),
('RecyclingCenter', 'LocalBusiness', 'A recycling center.', 'A recycling center.', 'Recycling Center', 'http://schema.org/RecyclingCenter', 0),
('Reservoir', 'BodyOfWater', '', '', 'Reservoir', 'http://schema.org/Reservoir', 0),
('Residence', 'Place', 'The place where a person lives.', 'The place where a person lives.', 'Residence', 'http://schema.org/Residence', 3),
('Restaurant', 'FoodEstablishment', 'A restaurant.', 'A restaurant.', 'Restaurant', 'http://schema.org/Restaurant', 0),
('Review', 'CreativeWork', 'A review of an item - for example, a restaurant, movie, or store.', 'A review of an item - for example, a restaurant, movie, or store.', 'Review', 'http://schema.org/Review', 0),
('RiverBodyOfWater', 'BodyOfWater', 'A river (for example, the broad majestic Shannon).', 'A river (for example, the broad majestic Shannon).', 'River Body Of Water', 'http://schema.org/RiverBodyOfWater', 0),
('RoofingContractor', 'HomeAndConstructionBusiness', 'A roofing contractor.', 'A roofing contractor.', 'Roofing Contractor', 'http://schema.org/RoofingContractor', 0),
('RVPark', 'CivicStructure', 'An RV park.', 'An RV park.', 'RV Park', 'http://schema.org/RVPark', 0),
('SaleEvent', 'Event', 'Event type: Sales event.', 'Event type: Sales event.', 'Sale Event', 'http://schema.org/SaleEvent', 0),
('ScholarlyArticle', 'Article', 'A scholarly article.', 'A scholarly article.', 'Scholarly Article', 'http://schema.org/ScholarlyArticle', 0),
('School', 'EducationalOrganization', 'A school.', 'A school.', 'School', 'http://schema.org/School', 0),
('Sculpture', 'CreativeWork', 'A piece of sculpture.', 'A piece of sculpture.', 'Sculpture', 'http://schema.org/Sculpture', 0),
('SeaBodyOfWater', 'BodyOfWater', 'A sea (for example, the Caspian sea).', 'A sea (for example, the Caspian sea).', 'Sea Body Of Water', 'http://schema.org/SeaBodyOfWater', 0),
('SearchResultsPage', 'WebPage', 'Web page type: Search results page.', 'Web page type: Search results page.', 'Search Results Page', 'http://schema.org/SearchResultsPage', 0),
('SelfStorage', 'LocalBusiness', 'Self-storage facility.', 'Self-storage facility.', 'Self Storage', 'http://schema.org/SelfStorage', 0),
('ShoeStore', 'Store', 'A shoe store.', 'A shoe store.', 'Shoe Store', 'http://schema.org/ShoeStore', 0),
('ShoppingCenter', 'LocalBusiness', 'A shopping center or mall.', 'A shopping center or mall.', 'Shopping Center', 'http://schema.org/ShoppingCenter', 0),
('SingleFamilyResidence', 'Residence', 'Residence type: Single-family home.', 'Residence type: Single-family home.', 'Single Family Residence', 'http://schema.org/SingleFamilyResidence', 0),
('SiteNavigationElement', 'WebPageElement', 'A navigation element of the page.', 'A navigation element of the page.', 'Site Navigation Element', 'http://schema.org/SiteNavigationElement', 0),
('SkiResort', 'SportsActivityLocation', 'A ski resort.', 'A ski resort.', 'Ski Resort', 'http://schema.org/SkiResort', 0),
('SocialEvent', 'Event', 'Event type: Social event.', 'Event type: Social event.', 'Social Event', 'http://schema.org/SocialEvent', 0),
('SportingGoodsStore', 'Store', 'A sporting goods store.', 'A sporting goods store.', 'Sporting Goods Store', 'http://schema.org/SportingGoodsStore', 0),
('SportsActivityLocation', 'LocalBusiness', 'A sports location, such as a playing field.', 'A sports location, such as a playing field.', 'Sports Activity Location', 'http://schema.org/SportsActivityLocation', 9),
('SportsClub', 'SportsActivityLocation', 'A sports club.', 'A sports club.', 'Sports Club', 'http://schema.org/SportsClub', 0),
('SportsEvent', 'Event', 'Event type: Sports event.', 'Event type: Sports event.', 'Sports Event', 'http://schema.org/SportsEvent', 0),
('SportsTeam', 'Organization', 'Organization: Sports team.', 'Organization: Sports team.', 'Sports Team', 'http://schema.org/SportsTeam', 0),
('StadiumOrArena', 'CivicStructure', 'A stadium.', 'A stadium.', 'Stadium Or Arena', 'http://schema.org/StadiumOrArena', 0),
('State', 'AdministrativeArea', 'A state or province.', 'A state or province.', 'State', 'http://schema.org/State', 0),
('Store', 'LocalBusiness', 'A retail good store.', 'A retail good store.', 'Store', 'http://schema.org/Store', 30),
('StructuredValue', 'Intangible', 'Structured values are stringsâ€”for example, addressesâ€”that have certain constraints on their structure.', 'Structured values are stringsâ€”for example, addressesâ€”that have certain constraints on their structure.', 'Structured Value', 'http://schema.org/StructuredValue', 3),
('SubwayStation', 'CivicStructure', 'A subway station.', 'A subway station.', 'Subway Station', 'http://schema.org/SubwayStation', 0),
('Synagogue', 'PlaceOfWorship', 'A synagogue.', 'A synagogue.', 'Synagogue', 'http://schema.org/Synagogue', 0),
('Table', 'WebPageElement', 'A table on the page.', 'A table on the page.', 'Table', 'http://schema.org/Table', 0),
('TattooParlor', 'HealthAndBeautyBusiness', 'A tattoo parlor.', 'A tattoo parlor.', 'Tattoo Parlor', 'http://schema.org/TattooParlor', 0),
('TaxiStand', 'CivicStructure', 'A taxi stand.', 'A taxi stand.', 'Taxi Stand', 'http://schema.org/TaxiStand', 0),
('TelevisionStation', 'LocalBusiness', 'A television station.', 'A television station.', 'Television Station', 'http://schema.org/TelevisionStation', 0),
('TennisComplex', 'SportsActivityLocation', 'A tennis complex.', 'A tennis complex.', 'Tennis Complex', 'http://schema.org/TennisComplex', 0),
('Text', 'DataType', 'Data type: Text.', 'Data type: Text.', 'Text', 'http://schema.org/Text', 1),
('TheaterEvent', 'Event', 'Event type: Theater performance.', 'Event type: Theater performance.', 'Theater Event', 'http://schema.org/TheaterEvent', 0),
('TheaterGroup', 'PerformingGroup', 'A theater group or companyâ€”for example, the Royal Shakespeare Company or Druid Theatre.', 'A theater group or companyâ€”for example, the Royal Shakespeare Company or Druid Theatre.', 'Theater Group', 'http://schema.org/TheaterGroup', 0),
('Thing', '', 'The most generic type of item.', 'The most generic type of item.', 'Thing', 'http://schema.org/Thing', 7),
('TireShop', 'Store', 'A tire shop.', 'A tire shop.', 'Tire Shop', 'http://schema.org/TireShop', 0),
('TouristAttraction', 'Place', 'A tourist attraction.', 'A tourist attraction.', 'Tourist Attraction', 'http://schema.org/TouristAttraction', 0),
('TouristInformationCenter', 'LocalBusiness', 'A tourist information center.', 'A tourist information center.', 'Tourist Information Center', 'http://schema.org/TouristInformationCenter', 0),
('ToyStore', 'Store', 'A toystore.', 'A toystore.', 'Toy Store', 'http://schema.org/ToyStore', 0),
('TrainStation', 'CivicStructure', 'A train station.', 'A train station.', 'Train Station', 'http://schema.org/TrainStation', 0),
('TravelAgency', 'LocalBusiness', 'A travel agency.', 'A travel agency.', 'Travel Agency', 'http://schema.org/TravelAgency', 0),
('TVEpisode', 'CreativeWork', 'An episode of a TV series or season.', 'An episode of a TV series or season.', 'TV Episode', 'http://schema.org/TVEpisode', 0),
('TVSeason', 'CreativeWork', 'A TV season.', 'A TV season.', 'TV Season', 'http://schema.org/TVSeason', 0),
('TVSeries', 'CreativeWork', 'A television series.', 'A television series.', 'TV Series', 'http://schema.org/TVSeries', 0),
('URL', 'Text', 'Data type: URL.', 'Data type: URL.', 'URL', 'http://schema.org/URL', 0),
('UserBlocks', 'UserInteraction', 'User interaction: Block this content.', 'User interaction: Block this content.', 'User Blocks', 'http://schema.org/UserBlocks', 0),
('UserCheckins', 'UserInteraction', 'User interaction: Check-in at a place.', 'User interaction: Check-in at a place.', 'User Checkins', 'http://schema.org/UserCheckins', 0),
('UserComments', 'UserInteraction', 'User interaction: A comment about an item.', 'User interaction: A comment about an item.', 'User Comments', 'http://schema.org/UserComments', 0),
('UserDownloads', 'UserInteraction', 'User interaction: Download of an item.', 'User interaction: Download of an item.', 'User Downloads', 'http://schema.org/UserDownloads', 0),
('UserInteraction', 'Event', 'A user interacting with a page', 'A user interacting with a page', 'User Interaction', 'http://schema.org/UserInteraction', 9),
('UserLikes', 'UserInteraction', 'User interaction: Like an item.', 'User interaction: Like an item.', 'User Likes', 'http://schema.org/UserLikes', 0),
('UserPageVisits', 'UserInteraction', 'User interaction: Visit to a web page.', 'User interaction: Visit to a web page.', 'User Page Visits', 'http://schema.org/UserPageVisits', 0),
('UserPlays', 'UserInteraction', 'User interaction: Play count of an item, for example a video or a song.', 'User interaction: Play count of an item, for example a video or a song.', 'User Plays', 'http://schema.org/UserPlays', 0),
('UserPlusOnes', 'UserInteraction', 'User interaction: +1.', 'User interaction: +1.', 'User Plus Ones', 'http://schema.org/UserPlusOnes', 0),
('UserTweets', 'UserInteraction', 'User interaction: Tweets.', 'User interaction: Tweets.', 'User Tweets', 'http://schema.org/UserTweets', 0),
('VeterinaryCare', 'MedicalOrganization', 'A vet''s office.', 'A vet''s office.', 'Veterinary Care', 'http://schema.org/VeterinaryCare', 0),
('VideoGallery', 'CollectionPage', 'Web page type: Video gallery page.', 'Web page type: Video gallery page.', 'Video Gallery', 'http://schema.org/VideoGallery', 0),
('VideoObject', 'MediaObject', 'A video file.', 'A video file.', 'Video Object', 'http://schema.org/VideoObject', 0),
('VisualArtsEvent', 'Event', 'Event type: Visual arts event.', 'Event type: Visual arts event.', 'Visual Arts Event', 'http://schema.org/VisualArtsEvent', 0),
('Volcano', 'Landform', 'A volcano, like Fuji san', 'A volcano, like Fuji san', 'Volcano', 'http://schema.org/Volcano', 0),
('Waterfall', 'BodyOfWater', 'A waterfall, like Niagara', 'A waterfall, like Niagara', 'Waterfall', 'http://schema.org/Waterfall', 0),
('WebPage', 'CreativeWork', 'A web page. Every web page is implicitly assumed to be declared to be of type WebPage, so the various properties about that webpage, such as <code>breadcrumb</code> may be used. We recommend explicit declaration if these properties are specified, but if they are found outside of an itemscope, they will be assumed to be about the page', 'A web page. Every web page is implicitly assumed to be declared to be of type WebPage, so the various properties about that webpage, such as breadcrumb may be used. We recommend explicit declaration if these properties are specified, but if they are found outside of an itemscope, they will be assumed to be about the page', 'Web Page', 'http://schema.org/WebPage', 7),
('WebPageElement', 'CreativeWork', '', '', 'Web Page Element', 'http://schema.org/WebPageElement', 6),
('WholesaleStore', 'Store', 'A wholesale store.', 'A wholesale store.', 'Wholesale Store', 'http://schema.org/WholesaleStore', 0),
('Winery', 'FoodEstablishment', 'A winery.', 'A winery.', 'Winery', 'http://schema.org/Winery', 0),
('WPAdBlock', 'WebPageElement', 'An advertising section of the page.', 'An advertising section of the page.', 'WP Ad Block', 'http://schema.org/WPAdBlock', 0),
('WPFooter', 'WebPageElement', 'The footer section of the page.', 'The footer section of the page.', 'WP Footer', 'http://schema.org/WPFooter', 0),
('WPHeader', 'WebPageElement', 'The header section of the page.', 'The header section of the page.', 'WP Header', 'http://schema.org/WPHeader', 0),
('WPSideBar', 'WebPageElement', 'A sidebar section of the page.', 'A sidebar section of the page.', 'WP Side Bar', 'http://schema.org/WPSideBar', 0),
('Zoo', 'CivicStructure', 'A zoo.', 'A zoo.', 'Zoo', 'http://schema.org/Zoo', 0);

CREATE TABLE IF NOT EXISTS `#__j4schema_type_prop` (
  `id_type` varchar(50) NOT NULL,
  `id_property` varchar(50) NOT NULL,
  PRIMARY KEY (`id_type`,`id_property`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `#__j4schema_type_prop` (`id_type`, `id_property`) VALUES
('AggregateOffer', 'highPrice'),
('AggregateOffer', 'lowPrice'),
('AggregateOffer', 'offerCount'),
('AggregateRating', 'itemReviewed'),
('AggregateRating', 'ratingCount'),
('AggregateRating', 'reviewCount'),
('Article', 'articleBody'),
('Article', 'articleSection'),
('Blog', 'blogPosts'),
('Book', 'bookEdition'),
('Book', 'bookFormat'),
('Book', 'illustrator'),
('Book', 'isbn'),
('Book', 'numberOfPages'),
('BookFormatType', 'EBook'),
('BookFormatType', 'Hardcover'),
('BookFormatType', 'Paperback'),
('Boolean', 'False'),
('Boolean', 'True'),
('CivicStructure', 'openingHours'),
('ContactPoint', 'contactType'),
('ContactPoint', 'email'),
('ContactPoint', 'faxNumber'),
('ContactPoint', 'telephone'),
('CreativeWork', 'about'),
('CreativeWork', 'aggregateRating'),
('CreativeWork', 'audio'),
('CreativeWork', 'author'),
('CreativeWork', 'awards'),
('CreativeWork', 'contentLocation'),
('CreativeWork', 'contentRating'),
('CreativeWork', 'datePublished'),
('CreativeWork', 'editor'),
('CreativeWork', 'encodings'),
('CreativeWork', 'genre'),
('CreativeWork', 'headline'),
('CreativeWork', 'inLanguage'),
('CreativeWork', 'interactionCount'),
('CreativeWork', 'isFamilyFriendly'),
('CreativeWork', 'keywords'),
('CreativeWork', 'offers'),
('CreativeWork', 'publisher'),
('CreativeWork', 'reviews'),
('CreativeWork', 'video'),
('EducationalOrganization', 'alumni'),
('Event', 'attendees'),
('Event', 'duration'),
('Event', 'endDate'),
('Event', 'location'),
('Event', 'offers'),
('Event', 'performers'),
('Event', 'startDate'),
('Event', 'subEvents'),
('Event', 'superEvent'),
('FoodEstablishment', 'acceptsReservations'),
('FoodEstablishment', 'menu'),
('FoodEstablishment', 'servesCuisine'),
('GeoCoordinates', 'elevation'),
('GeoCoordinates', 'latitude'),
('GeoCoordinates', 'longitude'),
('ImageObject', 'caption'),
('ImageObject', 'exifData'),
('ImageObject', 'representativeOfPage'),
('ImageObject', 'thumbnail'),
('ItemAvailability', 'Discontinued'),
('ItemAvailability', 'InStock'),
('ItemAvailability', 'InStoreOnly'),
('ItemAvailability', 'OnlineOnly'),
('ItemAvailability', 'OutOfStock'),
('ItemAvailability', 'PreOrder'),
('ItemList', 'itemListElement'),
('LocalBusiness', 'branchOf'),
('LocalBusiness', 'currenciesAccepted'),
('LocalBusiness', 'openingHours'),
('LocalBusiness', 'paymentAccepted'),
('LocalBusiness', 'priceRange'),
('MediaObject', 'bitrate'),
('MediaObject', 'contentSize'),
('MediaObject', 'contentURL'),
('MediaObject', 'duration'),
('MediaObject', 'embedURL'),
('MediaObject', 'encodesCreativeWork'),
('MediaObject', 'encodingFormat'),
('MediaObject', 'expires'),
('MediaObject', 'height'),
('MediaObject', 'playerType'),
('MediaObject', 'regionsAllowed'),
('MediaObject', 'requiresSubscription'),
('MediaObject', 'uploadDate'),
('MediaObject', 'width'),
('Movie', 'actors'),
('Movie', 'director'),
('Movie', 'duration'),
('Movie', 'musicBy'),
('Movie', 'producer'),
('Movie', 'productionCompany'),
('Movie', 'trailer'),
('MusicAlbum', 'byArtist'),
('MusicGroup', 'albums'),
('MusicGroup', 'musicGroupMember'),
('MusicGroup', 'tracks'),
('MusicPlaylist', 'numTracks'),
('MusicPlaylist', 'tracks'),
('MusicRecording', 'byArtist'),
('MusicRecording', 'duration'),
('MusicRecording', 'inAlbum'),
('MusicRecording', 'inPlaylist'),
('NutritionInformation', 'calories'),
('NutritionInformation', 'carbohydrateContent'),
('NutritionInformation', 'cholesterolContent'),
('NutritionInformation', 'fatContent'),
('NutritionInformation', 'fiberContent'),
('NutritionInformation', 'proteinContent'),
('NutritionInformation', 'saturatedFatContent'),
('NutritionInformation', 'servingSize'),
('NutritionInformation', 'sodiumContent'),
('NutritionInformation', 'sugarContent'),
('NutritionInformation', 'transFatContent'),
('NutritionInformation', 'unsaturatedFatContent'),
('Offer', 'aggregateRating'),
('Offer', 'availability'),
('Offer', 'itemCondition'),
('Offer', 'itemOffered'),
('Offer', 'price'),
('Offer', 'priceCurrency'),
('Offer', 'priceValidUntil'),
('Offer', 'reviews'),
('Offer', 'seller'),
('OfferItemCondition', 'DamagedCondition'),
('OfferItemCondition', 'NewCondition'),
('OfferItemCondition', 'RefurbishedCondition'),
('OfferItemCondition', 'UsedCondition'),
('Organization', 'address'),
('Organization', 'aggregateRating'),
('Organization', 'contactPoints'),
('Organization', 'email'),
('Organization', 'employees'),
('Organization', 'events'),
('Organization', 'faxNumber'),
('Organization', 'founders'),
('Organization', 'foundingDate'),
('Organization', 'interactionCount'),
('Organization', 'location'),
('Organization', 'members'),
('Organization', 'reviews'),
('Organization', 'telephone'),
('Person', 'address'),
('Person', 'affiliation'),
('Person', 'alumniOf'),
('Person', 'awards'),
('Person', 'birthDate'),
('Person', 'children'),
('Person', 'colleagues'),
('Person', 'contactPoints'),
('Person', 'deathDate'),
('Person', 'email'),
('Person', 'faxNumber'),
('Person', 'follows'),
('Person', 'gender'),
('Person', 'homeLocation'),
('Person', 'interactionCount'),
('Person', 'jobTitle'),
('Person', 'knows'),
('Person', 'memberOf'),
('Person', 'nationality'),
('Person', 'parents'),
('Person', 'performerIn'),
('Person', 'relatedTo'),
('Person', 'siblings'),
('Person', 'spouse'),
('Person', 'telephone'),
('Person', 'workLocation'),
('Person', 'worksFor'),
('Place', 'address'),
('Place', 'aggregateRating'),
('Place', 'containedIn'),
('Place', 'events'),
('Place', 'faxNumber'),
('Place', 'geo'),
('Place', 'interactionCount'),
('Place', 'maps'),
('Place', 'photos'),
('Place', 'reviews'),
('Place', 'telephone'),
('PostalAddress', 'addressCountry'),
('PostalAddress', 'addressLocality'),
('PostalAddress', 'addressRegion'),
('PostalAddress', 'postalCode'),
('PostalAddress', 'postOfficeBoxNumber'),
('PostalAddress', 'streetAddress'),
('Product', 'aggregateRating'),
('Product', 'brand'),
('Product', 'manufacturer'),
('Product', 'model'),
('Product', 'offers'),
('Product', 'productID'),
('Product', 'reviews'),
('Rating', 'bestRating'),
('Rating', 'ratingValue'),
('Rating', 'worstRating'),
('Recipe', 'cookingMethod'),
('Recipe', 'cookTime'),
('Recipe', 'ingredients'),
('Recipe', 'nutrition'),
('Recipe', 'prepTime'),
('Recipe', 'recipeCategory'),
('Recipe', 'recipeCuisine'),
('Recipe', 'recipeInstructions'),
('Recipe', 'recipeYield'),
('Recipe', 'totalTime'),
('Review', 'itemReviewed'),
('Review', 'reviewBody'),
('Review', 'reviewRating'),
('Thing', 'description'),
('Thing', 'image'),
('Thing', 'name'),
('Thing', 'url'),
('TVEpisode', 'actors'),
('TVEpisode', 'director'),
('TVEpisode', 'episodeNumber'),
('TVEpisode', 'musicBy'),
('TVEpisode', 'partOfSeason'),
('TVEpisode', 'partOfTVSeries'),
('TVEpisode', 'producer'),
('TVEpisode', 'productionCompany'),
('TVSeason', 'endDate'),
('TVSeason', 'episodes'),
('TVSeason', 'numberOfEpisodes'),
('TVSeason', 'partOfTVSeries'),
('TVSeason', 'seasonNumber'),
('TVSeason', 'startDate'),
('TVSeason', 'trailer'),
('TVSeries', 'actors'),
('TVSeries', 'director'),
('TVSeries', 'endDate'),
('TVSeries', 'episodes'),
('TVSeries', 'musicBy'),
('TVSeries', 'numberOfEpisodes'),
('TVSeries', 'producer'),
('TVSeries', 'productionCompany'),
('TVSeries', 'seasons'),
('TVSeries', 'startDate'),
('TVSeries', 'trailer'),
('VideoObject', 'caption'),
('VideoObject', 'thumbnail'),
('WebPage', 'breadcrumb'),
('WebPage', 'isPartOf'),
('WebPage', 'mainContentOfPage'),
('WebPage', 'primaryImageOfPage'),
('WebPage', 'significantLinks');

CREATE TABLE IF NOT EXISTS `#__j4schema_tokens` (
  `id_tokens` int(11) NOT NULL AUTO_INCREMENT,
  `to_integration` varchar(15) NOT NULL,
  `to_name` varchar(50) NOT NULL,
  `to_type` varchar(4) NOT NULL,
  `to_replace` varchar(255) NOT NULL,
  `enabled` tinyint(4) NOT NULL,
  PRIMARY KEY (`id_tokens`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=17 ;

INSERT INTO `#__j4schema_tokens` (`id_tokens`, `to_integration`, `to_name`, `to_type`, `to_replace`, `enabled`) VALUES
(1, 'joomla', 'ARTICLE_WRAPPER', 'text', 'itemscope itemtype="http://schema.org/WebPage"', 1),
(2, 'joomla', 'ARTICLE_BODY', 'text', ' itemprop="mainContentOfPage"', 1),
(3, 'joomla', 'ARTICLE_TITLE', 'text', ' itemprop="name"', 1),
(4, 'joomla', 'ARTICLE_LINK', 'text', ' itemprop="url"', 1),
(5, 'joomla', 'ARTICLE_CATEGORY', 'text', ' itemprop="genre"', 1),
(6, 'joomla', 'ARTICLE_LINKS', 'text', ' itemprop="significantLinks"', 1),
(7, 'joomla', 'ARTICLE_PUBLISH_UP', 'date', ' itemprop="datePublished"', 1),
(11, 'joomla', 'BLOG_ARTICLE_TITLE_LINK', 'text', ' itemprop="url"', 1),
(9, 'joomla', 'BLOG_ARTICLE_TITLE', 'text', 'itemprop="name"', 1),
(10, 'joomla', 'BLOG_POSTS_WRAPPER', 'text', 'itemscope itemtype="http://schema.org/BlogPosting" itemprop="mainContentOfPage"', 1),
(12, 'joomla', 'BLOG_CATEGORY', 'text', ' itemprop="articleSection"', 1),
(13, 'joomla', 'BLOG_TEXT_WRAPPER', 'text', ' itemprop="articleBody"', 1),
(14, 'joomla', 'BLOG_LINKS', 'text', ' itemprop="significantLinks"', 1),
(15, 'joomla', 'BLOG_WRAPPER', 'text', 'itemscope itemtype="http://schema.org/WebPage"', 1),
(16, 'joomla', 'BLOG_CHILDREN_LINK', 'text', ' itemprop="significantLinks"', 1);